### ISSUE TITLE
 Imported LB listener with no hostnames defined is always detecting change on plan/apply

### ISSUE THREAD

**Issue by jeliker** [terraform-providers/terraform-provider-oci#975] opened 2020-02-14 18:17 UTC
---
name: Imported LB listener with no hostnames defined is always detecting change on plan/apply
about: Imported LB listener with no hostnames defined sets hostname_names = null vs. setting hostname_names = []. This causes plan/apply to detect change every time though value never updates to [] when change is applied.
labels: bug
---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.9
+ provider.oci v3.62.0
+ provider.template v2.1.2

terraform-provider-oci 3.62.0

### Affected Resource(s)

oci_load_balancer_listener

### Terraform Configuration Files

```hcl
resource "oci_load_balancer_listener" "lb_sample" {
    default_backend_set_name = "${oci_load_balancer_backend_set.lb_sample.name}"
    load_balancer_id = "${oci_load_balancer_load_balancer.lb_sample.id}"
    name = "${var.common_name}"
    port = 80
    protocol = "HTTP"

    connection_configuration {
        idle_timeout_in_seconds = 60
        backend_tcp_proxy_protocol_version = null
    }
    hostname_names = null
    path_route_set_name = null
    rule_set_names = null
}
```

### Relevant state file data
```hcl
{
  "mode": "managed",
  "type": "oci_load_balancer_listener",
  "name": "lb_sample",
  "provider": "provider.oci",
  "instances": [
	{
	  "schema_version": 0,
	  "attributes": {
		"connection_configuration": [
		  {
			"backend_tcp_proxy_protocol_version": 0,
			"idle_timeout_in_seconds": "60"
		  }
		],
		"default_backend_set_name": "lb-sample",
		"hostname_names": null,
		"id": "loadBalancers/ocid1.loadbalancer.oc1.iad.someid/listeners/lb-sample",
		"load_balancer_id": "ocid1.loadbalancer.oc1.iad.someid",
		"name": "lb-sample",
		"path_route_set_name": null,
		"port": 80,
		"protocol": "HTTP",
		"rule_set_names": [],
		"ssl_configuration": [],
		"state": "SUCCEEDED",
		"timeouts": {
		  "create": null,
		  "delete": null,
		  "update": null
		}
	  },
	  "private": "sometext",
	  "depends_on": [
		"oci_load_balancer_backend_set.lb_sample",
		"oci_load_balancer_load_balancer.lb_sample"
	  ]
	}
  ]
}
```

Note that newly-created (not imported) oci_load_balancer_listener will have

```hcl
"hostname_names": []
```

…and does not see to have this issue of always detecting change. A work-around is to edit the state file to change the imported `hostname_names` from `null` to `[]`
### Expected Behavior

Imported LB listener with no hostnames defined should set state in same way as newly-created LB listener. That is, should set `hostname_names = []` not `hostname_names = null` as it is doing presently. 

### Actual Behavior

Imported LB listener with no hostnames defined imports state `hostname_names = null` instead of `hostname_names = []`. This causes all plan/apply to always detect change in `hostname_names`.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This only occurs with imported listener which sets "hostname_names": null. For new listener it creates "hostname_names": []

**Comment by parrneet** [comment] 2020-02-18 06:34
Hi @jeliker 
Thank you for reporting this. I'm able to reproduce this bug and trying to investigate the root cause. 
It could be a possible issue with Terraform v0.12 in the way diff is calculated for null TypeLists.
This is working for newly created LB because provider explicitly sets the hostnames to [] in create request and in that case service also return empty list([]) in response.

**Comment by parrneet** [comment] 2020-03-19 18:57
Hi @jeliker - The fix for this issue has been [released](https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.67.0).

**Closed by parrneet** 2020-03-19 18:57 UTC
Labels: bug, investigate
