### ISSUE TITLE
oci_core_volume: interpolated value for 'size_in_gbs' does not appear in plan

### ISSUE THREAD

**Issue by wmcdermid** [terraform-providers/terraform-provider-oci#607] opened 2018-09-19 22:17 UTC
### Terraform Version
0.11.8

### OCI Provider Version
2.2.x - 3.0.0

### Description:
Working w/ OCI Provider Version 2.1.17. Error occurs after upgrading to 2.2.0 or later (incl. 3.0.0):
While attempting to use an interpolated value for attribute `size_in_gbs` while provisioning an oci_core_volume resource, the value does not appear in the plan. This causes `terraform apply` to fail, with Terraform complaining that the "diffs didn't match during apply". Using a hard-coded value for `size_in_gbs` does not result in this discrepancy, but this is not a feasible workaround long-term. 

The error does not reproduce for all interpolation strings, it seems. The specific interpolation string that we use causes `size_in_gbs` to not appear in the plan. Simpler interpolation strings seem to work for `size_in_gbs`, but the strange thing is that using the problematic interpolation string for other attributes (e.g. `display_name`) does not cause the attribute to disappear from the plan...

### Terraform Plan
I have attached some of the plan output for the module I am provisioning (I can attach a full `terraform plan` output if necessary), along with the error output from Terraform during apply (one raw, one with a formatted diff from a single error). I have also attached a small snippet of TF code showing how the interpolation is structured.

[oci_core_volume-code-snippet.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2398881/oci_core_volume-code-snippet.txt)
[oci_core_volume-error-raw.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2398882/oci_core_volume-error-raw.txt)
[oci_core_volume-error-single.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2398883/oci_core_volume-error-single.txt)
[oci_core_volume-plan-snippet.txt](https://github.com/terraform-providers/terraform-provider-oci/files/2398884/oci_core_volume-plan-snippet.txt)

### Notes
Seems related to support for int64 for `size_in_gbs` in provider release 2.2.0, but I haven't gotten a chance to dig into this much.

Any help is greatly appreciated; let me know if you need additional details.

**Comment by alexng-canuck** [comment] 2018-09-21 04:58
I am able to repro this as well. Will require further investigation. The error implies that Terraform took two diffs for the `oci_core_volume` resource.
- one diff was taken before running the apply and does not yet know the value of `size_in_gbs` due to the use of interpolation. This diff is omitting `size_in_gbs`
- second diff was taken after computing the `size_in_gbs` from creating the `null_data_source`. This diff has the `size_in_gbs`

I suspect the introduction of DiffSuppression functions to the `size_in_gbs` has inadvertently changed the behavior of the first diff since v2.0.0.

**Comment by alexng-canuck** [comment] 2018-09-21 05:00
@wmcdermid does the apply succeed if you run it twice? 

I was able to get it to succeed after running `terraform apply` again presumably because the first apply stores all the needed data for computing `size_in_gbs` in the state file.

**Comment by alexng-canuck** [comment] 2018-09-28 22:51
The root cause is now understood. In 2.2 and above, we introduced a diff suppression behavior for supporting different representations of int64 values as strings. This suppression behavior was unexpectedly suppressing valid diffs in this scenario:
```
old value => ""
new value => "some interpolation syntax"
```

The result of both values is 0 in the string-to-int64 converter.

We are working on a fix for this.

**Comment by wmcdermid** [comment] 2018-10-03 19:19
@alexng-canuck That's great to hear! Sorry for the delay; a second run of `terraform apply` was another effective workaround, though not ideal long-term. Upgrading the provider has not been a high priority for us (yet), so this issue dropped off my radar for a bit.

Glad the cause is understood, and I will keep my eyes out for the fix!

**Comment by kilokahn** [comment] 2018-10-04 21:09
@wmcdermid - v3.3.0 is now released. Do you want to give this a shot?

**Comment by kilokahn** [comment] 2018-10-05 20:43
@wmcdermid I am closing this one, but let us know if you still face this issue.

**Closed by kilokahn** 2018-10-05 20:43 UTC
Labels: bug, regression, resolved

**Comment by wmcdermid** [comment] 2018-10-10 17:38
Thank you! No longer an issue under v3.3.0
