### ISSUE TITLE
Cannot Add Cost Tag Block Volumes Attached to Instances

### ISSUE THREAD

**Issue by tjkervin** [terraform-providers/terraform-provider-oci#639] opened 2018-11-02 21:06 UTC
### Terraform Version
<details>
Terraform v0.11.7
</details>

### OCI Provider Version

<details>
3.6
</details>

### Description:
I am attempting to apply cost tags via terraform to existing oci block volumes. The block Volumes are ISCSI attachments currently attached to running instances. When I add the defined tags to the block volume defnition in Terraform, i get an error saying that it cannot resize an instance that is already attached. I am making no other changes to the block volume other than the defined tag, so it's unclear to me why this error is occurring:
<details>
oci_core_volume.BV_STWMSQA1N2_1: Service error:Conflict. Volume ocid1.volume.oc1.iad.abuwcljtmaj65tkflpox5g6ybs5vfeh4noculgypxd3v76rxhrjnxzjptdia may not be resized while attached to an Instance.. http status code: 409. Opc request id: 63b0b0759ab80af3618e54766937f3a2/93FEB087FF8174B597D5832931E27593/F39499AE54EEF7AB548AE149E39385DD
</details>

It's worth noting too that I can apply these tags through the OCI console. 

### Terraform Plan

<details>
  ~ oci_core_volume.BV_STWMSQA2N1_1
      defined_tags.%:              "0" => "6"
      defined_tags.TagSpace.Tag1: "" => "tag1_val"
      defined_tags.TagSpace.Tag2: "" => "tag2_val"
      defined_tags.TagSpace.Tag3:      "" => "tag3_val"
      defined_tags.TagSpace.Tag4:     "" => "tag4_val"
      defined_tags.TagSpace.Tag5:      "" => "tag5_val"
      defined_tags.TagSpace.Tag6:        "" => "tag6_val"

</details>

**Comment by alexng-modules** [comment] 2018-11-02 22:18
FYI @rcohenma .

I think this issue is caused by a quirk in service API implementation for volumes. When you added the tags to the volume; this triggered an UpdateVolume request to the service. As part of the request the size of the volume was also sent (even though nothing changed there).

This caused the service to think that a resize needed to happen (but it cannot happen because the volume is attached). That is why you see the above error. However, the service should have detected that the size didn't change and should not have attempted a resize operation.

Note that this is specific to volumes. Adding defined tags to an instance or to any other resource does not trigger this behavior.

We will follow-up with the service on this behavior, but may need to consider a workaround to suppress sending the size when it hasn't changed.

**Comment by abhilash-av** [comment] 2018-11-08 22:20
We have a work around and it should be available next week.

**Comment by codycushing** [comment] 2018-11-15 22:32
Underlying issue of provider including `size_in_gbs` in the update request even when it has not changed has been addressed in 3.7.0 release. Please reopen if the problem persists.

**Closed by codycushing** 2018-11-15 22:32 UTC
Labels: bug
