### ISSUE TITLE
Update user-data should force new compute resource

### ISSUE THREAD

**Issue by matmacfarlane** [terraform-providers/terraform-provider-oci#673] opened 2018-12-19 15:01 UTC
### Terraform Version

Terraform v0.11.8

### OCI Provider Version

+ provider.oci v3.11.0

### Description:
When adding user-data to a core_instance resource block which previously had none, terraform attempts to update and change the resource. This fails with the following message:

* oci_core_instance.instance: Service error:InvalidParameter. The 'user_data' metadata field cannot be updated and must be provided with the already existing value.. 

### Terraform Plan

<details>
~ module.adf_server.oci_core_instance.instance
      metadata.user_data: "" => "IyEvYmluL2Jhc2gN......"

</details>

**Comment by bowfeng** [comment] 2018-12-19 18:44
@matmacfarlane Thanks for your feedback.
`user_data` and `ssh_authorized_keys` are immutable. To change 'ssh_authorized_keys' or 'user_data' properties in the 'metadata' field, the resource must be tainted and recreated.
Use the terraform "taint" command to target this resource then run apply again.
such as `terraform taint oci_core_instance.instance0` and then `terraform apply`

**Comment by matmacfarlane** [comment] 2018-12-19 18:53
So if this change requires a recreation, why not force a recreation?

**Comment by bowfeng** [comment] 2018-12-19 19:44
@matmacfarlane You made a good point, and we've already worked on it, and will release it in the near future to make updating user_data and ssh_authorized_keys force a recreation.

**Comment by matmacfarlane** [comment] 2018-12-19 19:46
@bowfeng thanks for the update!

**Comment by codycushing** [comment] 2019-01-09 02:31
The fix has been released in [v3.11.1](https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.11.1). You will now see force new behavior for that resource when changing `ssh_authorized_keys` or `user_data`

**Comment by ravitandonrt** [comment] 2019-01-10 21:36
Re-opening this issue as the customdiff in instance metadata caused a Terraform crash in case of using interpolations in metadata. Due to this we had to revert the change in v3.11.2

Next steps:
- Open a Terraform Core issue detailing the crash (Issue #685)
- Explore alternative ways to provide this functionality

**Comment by hatvik** [comment] 2019-01-16 12:19
Resource recreation caused by metadata changes, works with provider version 3.0.0.

This issue appeared with:
3.1.0 (September 20, 2018)
Added
Support for importing load balancer related resources such as backend, backend set, hostname, listeners, and path route sets
Support for updating an instance's metadata and extended metadata

Manually tainting resources is not a good workaround for us.

**Comment by ravitandonrt** [comment] 2019-01-16 17:52
@hatvik if you are not using interpolation in instance metadata then the release https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.11.1 would allow you you have the forceNew functionality on these two fields.

Right now, we are blocked on Terraform Issue https://github.com/hashicorp/terraform/issues/19978 to add customdiff that support interpolations as well.

Once we have a resolution for that issue we would put the fix back in to the provider for this issue.

**Comment by ravitandonrt** [comment] 2019-01-23 21:53
@matmacfarlane @hatvik - Can you try our latest release and let us know your feedback, this issue has been addressed as part of it: https://github.com/terraform-providers/terraform-provider-oci/releases/tag/v3.13.0

**Comment by ravitandonrt** [comment] 2019-02-01 22:39
Closing issue as the issue was fixed as of v3.13.0

**Closed by ravitandonrt** 2019-02-01 22:39 UTC
Labels: good workaround, question
