### ISSUE TITLE
DBaaS change data_storage_size gives an error for cpu_core_count 

### ISSUE THREAD

**Issue by tr-patrick** [terraform-providers/terraform-provider-oci#1034] opened 2020-04-18 07:58 UTC
# Terraform Version and Provider Version

- Terraform v0.12.20
- provider.oci v3.70.0
  
# Affected Resource(s)

oci_database_db_system

# Issue explanation
Perhaps related to issue #1026

You can change the data_storage_size_in_gb for a dbsystem online from 256 to 512. 

We changed this for the OTA environment which had VM.Standard2.1 shapes without problems. 

When we do the same thing for our production environment which has a shape VM.Standard2.2 we get an error related to the cpu_core_count. Which has absolutely nothing to do with the change we try to make. 

This is the change:
```
an execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.customer-prd-db1301.oci_database_db_system.instance will be updated in-place
  ~ resource "oci_database_db_system" "instance" {
        availability_domain     = "yDDt:EU-FRANKFURT-1-AD-1"
        backup_network_nsg_ids  = []
        compartment_id          = "ocid1.compartment.oc1........."
        cpu_core_count          = 2
        data_storage_percentage = 40
      ~ data_storage_size_in_gb = 256 -> 512
        database_edition        = "STANDARD_EDITION"
        defined_tags            = {
            "customer.Applicatie" = "xxx"
            "customer.Omgeving"   = "xxxx"
        }
        disk_redundancy         = "NORMAL"
        display_name            = "DB1"
        domain                  = "l3prod.customer.oraclevcn.com"
        fault_domains           = [
            "FAULT-DOMAIN-2",
        ]
        freeform_tags           = {
            "ServerType" = "Database server"
        }
        hostname                = "customer-prd-db1301"
        id                      = "ocid1.dbsystem.oc1.eu-frankfurt-1.jncorq"
        iorm_config_cache       = []
        license_model           = "LICENSE_INCLUDED"
        listener_port           = 1521
        node_count              = 1
        nsg_ids                 = []
        reco_storage_size_in_gb = 256
        scan_dns_record_id      = "ocid1.vcndnsrecord.oc1.eu-frankfurt-1.rvcwamttqq"
        scan_ip_ids             = []
        shape                   = "VM.Standard2.2"
        source                  = "NONE"
        ssh_public_keys         = [
            "...........................................",
        ]
        state                   = "AVAILABLE"
        subnet_id               = "ocid1.subnet.oc1.eu-frankfurt-1..................."
        time_created            = "2019-05-21 09:06:03.567 +0000 UTC"
        time_zone               = "UTC"
        version                 = "18.5.0.0.190115"
        vip_ids                 = []

        db_home {
            ...
            ...
            ...
        }

        db_system_options {
            storage_management = "ASM"
        }

        timeouts {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

When we apply we get the following error
```
module.customer-prd-db1301.oci_database_db_system.instance: Modifying... [id=ocid1.dbsystem.oc1.eu-frankfurt-1....]

Error: Service error:InvalidParameter. request.cpuCoreCount The number of CPU cores on an existing virtual machine DB system cannot be changed.. http status code: 400. Opc request id: .../.../...
```

In the state file the cpu_core_count is correct for the system
```
"module": "module.customer-prd-db1301",
      "mode": "managed",
      "type": "oci_database_db_system",
      "name": "instance",
      "provider": "provider.oci",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "availability_domain": "yDDt:EU-FRANKFURT-1-AD-1",
            "backup_network_nsg_ids": [],
            "backup_subnet_id": null,
            "cluster_name": null,
            "compartment_id": "...",
            "cpu_core_count": 2,           <-- this is correct with the shape 2.2
            "data_storage_percentage": 40,
            "data_storage_size_in_gb": 256,  <-- size we want to change
```

# Expected behavior
On the VM.Standard2.1 shapes we had no issues. On this shape we get an error. The VM dbsystems shapes have a 1 to 1 relation with cpu_core_count with no influence to change as a user. 

We want to increase storage. 

# Workaround
I tried to give the variable cpu_core_count = 2 with our module which worked for issue #1026, but it didn't work now. 

We can't change the storage size of the DBsystem which is getting critical now.

**Comment by afedorch** [comment] 2020-04-18 18:52
Duplicate of #1026

**Closed by afedorch** 2020-04-18 18:52 UTC
Labels: bug
