### ISSUE TITLE
backupNetworkNsgIds : is not supported with current shape, when defining managed backups

### ISSUE THREAD

**Issue by dhoogfr** [terraform-providers/terraform-provider-oci#834] opened 2019-07-29 15:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
[root@terraform01 test]# terraform -v
Terraform v0.11.13
+ provider.oci v3.35.0

### Affected Resource(s)
oci_database_db_system

### Terraform Configuration Files

```
resource "oci_database_db_system" "bagdbrst" {
  compartment_id          = "${oci_identity_compartment.bagsup_test.id}"
  availability_domain     = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains["${var.tst_ad}"],"name")}"
  fault_domains           = ["${lookup(data.oci_identity_fault_domains.FDs.fault_domains["${var.tst_fd}"],"name")}"]
  hostname                = "rest"
  shape                   = "${var.db_bagdb_shape}"
  ssh_public_keys         = ["${var.ssh_public_key_samsonite_bagsupport}"]
  subnet_id               = "${oci_core_subnet.bagsup_tst1.id}"
  license_model           = "LICENSE_INCLUDED"
  node_count              = "1"
  database_edition        = "STANDARD_EDITION"
  data_storage_size_in_gb = "${var.db_bagdb_storage_gb}"

  db_home {
    database {
      admin_password = "${var.db_bagdb_admin_password}"

      character_set  = "AL32UTF8"
      ncharacter_set = "AL16UTF16"
      db_name        = "${var.db_bagdb_db_name}"

      pdb_name = "devap"

      db_backup_config {
        auto_backup_enabled     = "true"
        recovery_window_in_days = 30
      }

    }

    db_version = "18.6.0.0.190416"
  }
  defined_tags = "${var.common_tags}"
  timeouts {
    create = "180m"
  }
}

```

### Actual Behavior

Error: Error applying plan:

1 error(s) occurred:

* oci_database_db_system.bagdbrst: 1 error(s) occurred:

* oci_database_db_system.bagdbrst: Service error:InvalidParameter. backupNetworkNsgIds : is not supported with current shape.. http status code: 400. Opc request id: d05cf68761763d1e2578a2d424463004/A4EB04801FFBD09824AFC2AC6615BB53/C1D801DD845E53780DAFDBD2C34E3204

While it is correct that the backup network is not supported in this shape, it is also not required for managed backups. So the correct behavior would be to enable the managed backups without dedicated backup network (as is done when enabling it via the console.

### Steps to Reproduce

* create dbcs virtual guest without enabling managed backups
* update the config to enable managed backups

**Comment by kilokahn** [comment] 2019-07-29 15:49
hey @dhoogfr - thanks for reporting this. can you please share the exact shape that you are using?

Also, can you please help out with the debug logs for the operation that you are performing (using instructions at https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider )

In the meantime, I will try to reproduce this in a development setup.

**Comment by dhoogfr** [comment] 2019-07-29 16:15
Hi,

The shape is a VM.Standard2.2
I'm checking for the debug logs, but I don't know if I can share them in full
It seems to also log all the security list rules and such

**Comment by kilokahn** [comment] 2019-07-29 16:20
Thanks @dhoogfr - we will use this shape to repro. If the debug logs don't have any sensitive information, you can send it to mukarram.baig@oracle.com for quicker troubleshooting.

**Comment by dhoogfr** [comment] 2019-07-29 16:54
Hi, I have send the debug log to the mentioned email address.

In the initial statement I said the that the problem was with the backup network itself.
But looking at the log I realize that this is not correct. The problem is with the network security group for the backup network, not with the backup network itself.

From the output, I can see it sets the bagkupNetworkNsgIds (which are not in the TF script) to an empty list.
It is unclear for me if OCI should actually complain on an empty list, even if this feature is not available for the selected shape....

```

2019/07/29 16:29:09 [DEBUG] Interpolating computed list element attribute fault_domains (3)^M
^[[0m^[[1moci_database_db_system.bagdbrst: Modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq)^[[0m^M
  db_home.0.database.0.db_backup_config.#:                         "0" => "1"^M
  db_home.0.database.0.db_backup_config.0.auto_backup_enabled:     "" => "true"^M
  db_home.0.database.0.db_backup_config.0.recovery_window_in_days: "" => "30"^[[0m^M
2019-07-29T16:29:09.657Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655173 asm_amd64.s:1337: operation attempt #1^M
2019-07-29T16:29:09.658Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655253 http.go:604: Marshaling to Request: UpdateDbSystemRequest^M
2019-07-29T16:29:09.658Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655333 http.go:538: Marshaling to path from field: DbSystemId in template: /dbSystems/{dbSystemId}^M
2019-07-29T16:29:09.658Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655353 http.go:542: Marshaling to body from field:UpdateDbSystemDetails^M
2019-07-29T16:29:09.659Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655613 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: CpuCoreCount^M
2019-07-29T16:29:09.659Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655638 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: Version^M
2019-07-29T16:29:09.659Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655681 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: SshPublicKeys^M
2019-07-29T16:29:09.659Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655696 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: DataStorageSizeInGBs^M
2019-07-29T16:29:09.660Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655709 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: FreeformTags^M
2019-07-29T16:29:09.660Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655722 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: DefinedTags^M
2019-07-29T16:29:09.660Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655740 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: NsgIds^M
2019-07-29T16:29:09.660Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655765 http.go:160: Adjusting tag: mandatory is false and json tag is valid on field: BackupNetworkNsgIds^M
2019-07-29T16:29:09.661Z [DEBUG] plugin.terraform-provider-oci_v3.35.0: DEBUG 2019/07/29 16:29:09.655835 http.go:542: Marshaled body is: {"backupNetworkNsgIds":[],"cpuCoreCount":2,"definedTags":{"Samsonite":{"costcenter":"Bagsupport","lifecycle":"Test"}},"freeformTags":{},"nsgIds":[],"sshPublicKeys":["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCthd22WPi2JpsVAdnBHdQEqBEjFatBzsU9Bk+3gn8QIW+lag7MzHlcs8OPA69jdjTLqtPm6J6+9B7PtgOdpoQoYHX6WC2C9robHBQ2aVhztW3dUMo3AefpceA/QoLMKQJHvcPIWNJPkKquDCHzPdZbwaPw9IVWIuwyyxWD3vQQG67AalqkXZIQTvyznCv/+Jr8mqoTwQdt+wHi0dKBYZ61ddsf4eGjSn4ygZo2OdiITofSShRE7M7V0O+3yPf/P19FjcGMUOZqNoEKyS37hGxGWMefVjccNlP++sBkcPvykzHE/ask0832mgT65Qgg1otQqU20AwKVdwot5SaGtD6v dhoogfr@dhoogfr-lpt1"]}^M

```

**Comment by kilokahn** [comment] 2019-07-29 18:06
Thanks for the debug logs @dhoogfr - we are working with the database team to resolve this.

**Comment by kornholjo** [comment] 2019-07-29 19:04
I'm getting the same error:
```
 Error: Service error:InvalidParameter. backupNetworkNsgIds : is not supported with current shape.. http status code: 400. Opc request id: *****REMOVED******

  on ../../../../../modules/global/database/database.tf line 51, in resource "my_db_system" "db_system":
  51: resource "oci_database_db_system" "db_system" {

```
 Is it possible that this problem somehow related to a recent change? The same terraform script worked fine few days a ago.

**Comment by kilokahn** [comment] 2019-07-29 19:09
Yes, this looks like a recent regression, and the service team is working on deploying a fix soon.

**Comment by varmax2511** [comment] 2019-07-30 08:30
A fix has been deployed by the service team. Can you please let us know if the issue still persists?

**Comment by dhoogfr** [comment] 2019-07-30 08:38
Hi,

I can confirm that the issue has been resolved.
Thank you for the swift action

```

[root@terraform01 test]# terraform apply ./tf_fdh2 
oci_database_db_system.bagdbrst: Modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq)
  db_home.0.database.0.db_backup_config.#:                         "0" => "1"
  db_home.0.database.0.db_backup_config.0.auto_backup_enabled:     "" => "true"
  db_home.0.database.0.db_backup_config.0.recovery_window_in_days: "" => "30"
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 10s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 20s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 30s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 40s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 50s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 1m0s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 1m10s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 1m20s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 1m30s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 1m40s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 1m50s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 2m0s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 2m10s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 2m20s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 2m30s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 2m40s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 2m50s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 3m0s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 3m10s elapsed)
oci_database_db_system.bagdbrst: Still modifying... (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq, 3m20s elapsed)
oci_database_db_system.bagdbrst: Modifications complete after 3m20s (ID: ocid1.dbsystem.oc1.eu-frankfurt-1.abthe...qm2uhfpjt7eoaojpa4fxt4dpjde77v64clhkgq)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

**Comment by kornholjo** [comment] 2019-07-30 18:58
Fixed confirmed, the terraform scripts which previously was reporting errors (database) finishes without any problems. Thanks.

**Comment by varmax2511** [comment] 2019-07-30 23:05
Thanks @dhoogfr and @kornholjo for confirming the fix and thank you for your patience. I will be closing this ticket now.

**Closed by varmax2511** 2019-07-30 23:05 UTC
Labels: bug
