### ISSUE TITLE
db_home not recognised after importing a db system

### ISSUE THREAD

**Issue by lucianf** [terraform-providers/terraform-provider-oci#830] opened 2019-07-24 13:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

```
Terraform v0.11.14
+ provider.oci v3.34.0
+ provider.template v2.1.2
```

### Affected Resource(s)

`oci_database_db_system`

### Terraform Configuration Files

An existing OCI resource has been imported for the tf resource below:

```hcl
resource "oci_database_db_system" "xxx_db_system" {
    availability_domain = "${var.ad_list["AD2"]}"
    compartment_id = "${oci_identity_compartment.xxx.id}"
    database_edition = "ENTERPRISE_EDITION"
    db_home {
        database {
            admin_password = "xxx"
            character_set = "AL32UTF8"
            db_backup_config {
                auto_backup_enabled = "true"
                recovery_window_in_days = "15"
            }
            db_name = "xxx"
            db_workload = "DSS"
            defined_tags = { "xxx.xxx" = "xxx"}
            freeform_tags = { "XXX" = "xxx"}
            ncharacter_set = "AL16UTF16"
            pdb_name = "xxxpdb"
        }
		
	db_version = "12.2.0.1.190115"
    }
    hostname = "xxx"
    shape = "VM.Standard2.1"
    ssh_public_keys = ["${file(var.authorized_keys_path)}"]
    subnet_id = "${oci_core_subnet.xxx_sn.id}"

    lifecycle {
       ignore_changes = ["db_home.0.database.0.admin_password","db_home.0.database.0.backup_tde_password"]
    }
}
```

### State

Here's how the resource looks in the `terraform.state` file:

```
"oci_database_db_system.xxx_db_system": {
    "type": "oci_database_db_system",
    "depends_on": [],
    "primary": {
        "id": "ocid1.dbsystem.oc1.uk-london-1.[...]yuama",
        "attributes": {
            "availability_domain": "GyaU:UK-LONDON-1-AD-2",
            "backup_network_nsg_ids.#": "0",
            "compartment_id": "ocid1.compartment.oc1..xxx",
            "cpu_core_count": "1",
            "data_storage_percentage": "80",
            "data_storage_size_in_gb": "1024",
            "database_edition": "ENTERPRISE_EDITION",
            "db_home.#": "1",
            "db_home.0.database.#": "1",
            "db_home.0.database.0.admin_password": "",
            "db_home.0.database.0.backup_id": "",
            "db_home.0.database.0.backup_tde_password": "",
            "db_home.0.database.0.character_set": "AL32UTF8",
            "db_home.0.database.0.connection_strings.#": "1",
            "db_home.0.database.0.connection_strings.0.all_connection_strings.%": "2",
            "db_home.0.database.0.connection_strings.0.all_connection_strings.cdbDefault": "xxx.yyy.zzz.oraclevcn.com:1521/xxx_lhr2k8.yyy.zzz.oraclevcn.com",
            "db_home.0.database.0.connection_strings.0.all_connection_strings.cdbIpDefault": "(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=10.x.x.x)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=xxx_lhr2k8.yyy.zzz.oraclevcn.com)))",
            "db_home.0.database.0.connection_strings.0.cdb_default": "xxx.yyy.zzz.oraclevcn.com:1521/xxx_lhr2k8.yyy.zzz.oraclevcn.com",
            "db_home.0.database.0.connection_strings.0.cdb_ip_default": "(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=10.x.x.x)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=xxx_lhr2k8.yyy.zzz.oraclevcn.com)))",
            "db_home.0.database.0.db_backup_config.#": "1",
            "db_home.0.database.0.db_backup_config.0.auto_backup_enabled": "true",
            "db_home.0.database.0.db_backup_config.0.recovery_window_in_days": "15",
            "db_home.0.database.0.db_name": "xxx",
            "db_home.0.database.0.db_unique_name": "xxx_lhr2k8",
            "db_home.0.database.0.db_workload": "DSS",
            "db_home.0.database.0.defined_tags.%": "0",
            "db_home.0.database.0.freeform_tags.%": "0",
            "db_home.0.database.0.id": "ocid1.database.oc1.uk-london-1.[...]ck7wq",
            "db_home.0.database.0.lifecycle_details": "The database restore operation failed. Run 'dbcli list-jobs' on all hosts in the DB system to check for problems and fix them before rerunning the operation.",
            "db_home.0.database.0.ncharacter_set": "AL16UTF16",
            "db_home.0.database.0.pdb_name": "xxxpdb",
            "db_home.0.database.0.state": "AVAILABLE",
            "db_home.0.database.0.time_created": "2019-03-19 12:28:25.559 +0000 UTC",
            "db_home.0.db_version": "12.2.0.1.190115",
            "db_home.0.display_name": "dbhome20190319122825",
            "db_home.0.id": "ocid1.dbhome.oc1.uk-london-1.[...]s7fwq",
            "db_home.0.last_patch_history_entry_id": "ocid1.dbpatchhistory.oc1.uk-london-1.[...]pg4xq",
            "db_home.0.state": "AVAILABLE",
            "db_home.0.time_created": "2019-03-19 12:28:25.558 +0000 UTC",
            "defined_tags.%": "1",
            "defined_tags.xxx.xxx": "xxx",
            "disk_redundancy": "HIGH",
            "display_name": "xxx",
            "domain": "yyy.zzz.oraclevcn.com",
            "fault_domains.#": "1",
            "fault_domains.0": "FAULT-DOMAIN-2",
            "freeform_tags.%": "1",
            "freeform_tags.XXX": "xxx",
            "hostname": "xxx",
            "id": "ocid1.dbsystem.oc1.uk-london-1.[...]yuama",
            "iorm_config_cache.#": "0",
            "last_patch_history_entry_id": "ocid1.dbpatchhistory.oc1.uk-london-1.[...]glzva",
            "license_model": "BRING_YOUR_OWN_LICENSE",
            "listener_port": "1521",
            "node_count": "1",
            "nsg_ids.#": "0",
            "reco_storage_size_in_gb": "256",
            "scan_dns_record_id": "ocid1.vcndnsrecord.oc1.uk-london-1.[...]awzeq",
            "scan_ip_ids.#": "0",
            "shape": "VM.Standard2.1",
            "source": "NONE",
            "ssh_public_keys.#": "1",
            "ssh_public_keys.0": "ssh-rsa AAAAxxx",
            "state": "AVAILABLE",
            "subnet_id": "ocid1.subnet.oc1.uk-london-1.[...]2u6sa",
            "time_created": "2019-03-19 12:28:25.556 +0000 UTC",
            "time_zone": "UTC",
            "version": "12.2.0.1.190416",
            "vip_ids.#": "0"
        },
        "meta": {
            "e2bfb730-ecaa-11e6-8f88-34363bc7c4c0": {
                "create": 0,
                "delete": 7200000000000,
                "update": 7200000000000
            }
        },
        "tainted": false
    },
    "deposed": [],
    "provider": "provider.oci"
},
```

The `oci_database_db_system` including the `db_home` seems to have been imported just fine.

### Expected Behavior

Upon the next plan/apply no diff should be raised since all properties match.

### Actual Behavior

The following diff is raised:

```
+oci_database_db_system.xxx_db_system
      db_home.#:                                                           "1"
      db_home.0.database.#:                                                "1"
      db_home.0.database.0.admin_password:                                 <sensitive>
      db_home.0.database.0.backup_id:                                      <computed>
      db_home.0.database.0.backup_tde_password:                            <computed>
      db_home.0.database.0.character_set:                                  "AL32UTF8"
      db_home.0.database.0.connection_strings.#:                           <computed>
      db_home.0.database.0.db_backup_config.#:                             "1"
      db_home.0.database.0.db_backup_config.0.auto_backup_enabled:         "true"
      db_home.0.database.0.db_backup_config.0.recovery_window_in_days:     "15"
      db_home.0.database.0.db_name:                                        "xxx"
      db_home.0.database.0.db_unique_name:                                 <computed>
      db_home.0.database.0.db_workload:                                    "DSS"
      db_home.0.database.0.defined_tags.%:                                 "1"
      db_home.0.database.0.defined_tags.xxx.xxx:                           "xxx"
      db_home.0.database.0.freeform_tags.%:                                "1"
      db_home.0.database.0.freeform_tags.XXX:                              "xxx"
      db_home.0.database.0.id:                                             <computed>
      db_home.0.database.0.lifecycle_details:                              <computed>
      db_home.0.database.0.ncharacter_set:                                 "AL16UTF16"
      db_home.0.database.0.pdb_name:                                       "dev1pdb"
      db_home.0.database.0.state:                                          <computed>
      db_home.0.database.0.time_created:                                   <computed>
      db_home.0.db_version:                                                "12.2.0.1.190115"
      db_home.0.display_name:                                              <computed>
      db_home.0.id:                                                        <computed>
      db_home.0.last_patch_history_entry_id:                               <computed>
      db_home.0.state:                                                     <computed>
      db_home.0.time_created:                                              <computed>


Plan: 1 to add, 0 to change, 0 to destroy.
```

The OCI provider doesn't seem to pick the existing `db_home` and is trying to create it from scratch.

Since the `db_home` is defined as part of the `oci_database_db_system` there doesn't seem to be a way to import it separately (as an `oci_database_db_home`) even though it does have an OCID.

Am I missing something or is this a bug?

**Comment by kilokahn** [comment] 2019-07-24 13:14
hey @lucianf  - can you please check if https://www.terraform.io/docs/providers/oci/r/database_db_system.html#import answers some of your questions?

**Comment by kilokahn** [comment] 2019-07-24 13:18
ah - i see that you have already ignored the said attribute. let me repro that setup on my end.

**Comment by kilokahn** [comment] 2019-07-24 13:29
just a guess - could it be that `"version": "12.2.0.1.190416"` (in imported) vs `"version": "12.2.0.1.190115"` (in config) is causing the db_home to be recreated (because it is not an updatable parameter)?

**Comment by lucianf** [comment] 2019-07-24 13:39
Thanks @kilokahn but that's not it.

First of all, the strange thing is that it's not doing a destroy and recreate, but rather a create from scratch (as if the existing db_home didn't even exist - note that even the `db_home.# = 1` is listed as a change).

Secondly, `version` <> `db_version`.  It's the `db_version` that's `12.2.0.1.190115` and it matches the property in the state.  `12.2.0.1.190416` is the DB System Version, that's a different property that sits one level up.  It's not set up in the `.tf` so I can only assume the current value is the defaulted version.

**Comment by kilokahn** [comment] 2019-07-24 15:21
Thanks for the quick reply @lucianf. From the message:
```
"The database restore operation failed. Run 'dbcli list-jobs' on all hosts in the DB system to check for problems and fix them before rerunning the operation.",
```
it may seem that the import operation was not successful. Since the db_system has the nested db_home (and further nested database resource), the import is not a trivial operation (since it has to figure out the association between the db_system and db_home from more coarse grained APIs). Can you please help out by providing the logs for the `import` command (using instructions at https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider)? Thanks!

**Comment by lucianf** [comment] 2019-07-24 16:01
No that message has nothing to do with the terraform import. It comes (via the OCI API) from the OS, specifically from the cloud database service (DBaaS). It simply provides the latest snapshot on an action carried within the database - where a db restore was attempted and failed. No relation to db system or db home resource provisioning through the OCI API or the terraform OCI provider.

**Comment by lucianf** [comment] 2019-07-24 16:03
Also as you can see in the state, the db home details were retrieved in full during the import, and are associated with the db system. There doesn't seem to be anything wrong with the import, the data is there.

**Comment by kilokahn** [comment] 2019-07-25 00:27
I see your point. 

I tried to reproduce it on my side, but I didn't see this problem (saw other problems related to `node_count` and `data_storage_size_in_gb` though). For avoidance of doubt, can you please share the logs for `import` and `plan` steps with verbose logging?

**Comment by kilokahn** [comment] 2019-07-26 20:51
The issue seems to be a mismatch between the `freeform_tags` and `defined_tags` on the `database` in the config and the state file. Terraform could have done a better job in showing the diff and I will raise a ticket with the Hashicorp folks for it.

**Comment by kilokahn** [comment] 2019-07-26 22:59
The diff for this case when using v0.12 is quite precise (see below for a change in db_system.db_home.database.freeform_tags). Since the root cause has been identified and future users can use v0.12 terraform executable and see the better diff.

*In v0.11.14:*
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
+ oci_database_db_system.test_db_system
      db_home.#:                                                       "1"
      db_home.0.database.#:                                            "1"
      db_home.0.database.0.admin_password:                             <sensitive>
      db_home.0.database.0.backup_id:                                  <computed>
      db_home.0.database.0.backup_tde_password:                        <computed>
      db_home.0.database.0.character_set:                              "AL32UTF8"
      db_home.0.database.0.connection_strings.#:                       <computed>
      db_home.0.database.0.db_backup_config.#:                         "1"
      db_home.0.database.0.db_backup_config.0.auto_backup_enabled:     "true"
      db_home.0.database.0.db_backup_config.0.recovery_window_in_days: "10"
      db_home.0.database.0.db_name:                                    "aTFdb"
      db_home.0.database.0.db_unique_name:                             <computed>
      db_home.0.database.0.db_workload:                                "OLTP"
      db_home.0.database.0.freeform_tags.%:                            "1"
      db_home.0.database.0.freeform_tags.Department:                   "Finance2"
      db_home.0.database.0.id:                                         <computed>
      db_home.0.database.0.lifecycle_details:                          <computed>
      db_home.0.database.0.ncharacter_set:                             "AL16UTF16"
      db_home.0.database.0.pdb_name:                                   "pdbName"
      db_home.0.database.0.state:                                      <computed>
      db_home.0.database.0.time_created:                               <computed>
      db_home.0.db_version:                                            "12.1.0.2"
      db_home.0.display_name:                                          "MyTFDBHome"
      db_home.0.id:                                                    <computed>
      db_home.0.last_patch_history_entry_id:                           <computed>
      db_home.0.state:                                                 <computed>
      db_home.0.time_created:                                          <computed>
Plan: 1 to add, 0 to change, 0 to destroy.
``` 
*In v0.12.5:*
```
  # oci_database_db_system.test_db_system will be updated in-place
  ~ resource "oci_database_db_system" "test_db_system" {
        availability_domain         = "NyKp:PHX-AD-1"
        backup_network_nsg_ids      = []
        compartment_id              = "ocid1.compartment.oc1..aaaaaaaaso3da5o2bcbhr7jfzkdmndb7dk5ckjzhoz5yutjuyohgpvdfduuq"
        cpu_core_count              = 2
        data_storage_percentage     = 40
        database_edition            = "ENTERPRISE_EDITION"
        defined_tags                = {}
        disk_redundancy             = "HIGH"
        display_name                = "MyTFDBSystem"
        domain                      = "tfexsubdbsys.tfexvcndbsys.oraclevcn.com"
        fault_domains               = [
            "FAULT-DOMAIN-2",
        ]
        freeform_tags               = {
            "Department" = "Finance"
        }
        hostname                    = "myoracledb"
        id                          = "ocid1.dbsystem.oc1.phx.abyhqljsqwgt25uodprbauzarl2ze2nzroaxdqkbeg6dg3atdyvuoatxkzka"
        iorm_config_cache           = []
        last_patch_history_entry_id = "ocid1.dbpatchhistory.oc1.phx.abyhqljscjy32mue3xbdvc4f5d57456wbnod3iyukdm264n2x2nggchyqlca"
        license_model               = "LICENSE_INCLUDED"
        listener_port               = 1521
        nsg_ids                     = []
        scan_ip_ids                 = []
        shape                       = "BM.DenseIO2.52"
        source                      = "NONE"
        ssh_public_keys             = [
            "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3WqtQr7ZnH3fvtA+pQ0i7bIIQkuK/E4JnGkzQPNFpynpB2KLkYE+l27ONgXjhbYgc0fCPr3btCn1kzE9cYOqIsXECJRPntpSS6Zk+YS1rqGR4tMBm+2g+EpuvzXaMHTy7ZIiSD+Svw+gfPaJBG8O9bQzYxdPRmTDqgv0TKHoXbMqaWY2277xuPRPNIvHetOMbmioAz9sfDMmQETt6XtcLNlITCG/CALC/MHTnKbu8fHFypliciDXJ5KoWG2PNWMZIDbEBYVEwWf/f252WnyPXq3FVa4DDj/OWvS5IAicmK55Yv4D8ua3655BeVPHRVjpEczy5I0Tg3qPw06SFsA/X tf-test-instance-key",
        ]
        state                       = "AVAILABLE"
        subnet_id                   = "ocid1.subnet.oc1.phx.aaaaaaaa2edbhbjfosa74dbn3o7fqtrsnbnky33jcvy6hvpmxybok2p3lcnq"
        time_created                = "2019-07-26 22:40:42.787 +0000 UTC"
        time_zone                   = "UTC"
        version                     = "12.2.0.1.170117"
        vip_ids                     = []      ~ db_home {
            db_version   = "12.1.0.2"
            display_name = "MyTFDBHome"
            id           = "ocid1.dbhome.oc1.phx.abyhqljsk5tmafirtafgo26cwpt3leyjm46ij7hxu7yukwivg6ljaiygmxza"
            state        = "AVAILABLE"
            time_created = "2019-07-26 22:40:42.789 +0000 UTC"          ~ database {
                character_set      = "AL32UTF8"
                connection_strings = [
                    {
                        all_connection_strings = {
                            "cdbDefault" = "myoracledb.tfexsubdbsys.tfexvcndbsys.oraclevcn.com:1521/aTFdb_phx1vv.tfexsubdbsys.tfexvcndbsys.oraclevcn.com"
                        }
                        cdb_default            = "myoracledb.tfexsubdbsys.tfexvcndbsys.oraclevcn.com:1521/aTFdb_phx1vv.tfexsubdbsys.tfexvcndbsys.oraclevcn.com"
                        cdb_ip_default         = ""
                    },
                ]
                db_name            = "aTFdb"
                db_unique_name     = "aTFdb_phx1vv"
                db_workload        = "OLTP"
                defined_tags       = {}
              ~ freeform_tags      = {
                  + "Department" = "Finance2"
                }
                id                 = "ocid1.database.oc1.phx.abyhqljslynvix24b2quqmwib5ohx26jkczkma5tho4ulohbpxs2hsxcuuzq"
                ncharacter_set     = "AL16UTF16"
                pdb_name           = "pdbName"
                state              = "AVAILABLE"
                time_created       = "2019-07-26 22:40:42.79 +0000 UTC"                db_backup_config {
                    auto_backup_enabled     = true
                    recovery_window_in_days = 10
                }
            }
        }        timeouts {}
    }
Plan: 0 to add, 1 to change, 0 to destroy.
``` 

I am closing this out, but let us know if you need any other help.

**Closed by kilokahn** 2019-07-26 22:59 UTC
