### ISSUE TITLE
Error: timeout - last error: dial tcp from null_ressource

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#868] opened 2019-09-05 18:09 UTC
resource "null_resource" "cluster" {
  count = 4
  connection {
    type        = "ssh"
    host        = "${element( flatten(list(oci_core_instance.ebs_instance.*.public_ip)) , count.index)}"
    user        = "opc"
    private_key = "${file("~/.ssh/priv.txt")}"
  }  

    provisioner "file" {
    source      = "init.sh"
    destination = "/tmp/init.sh"
    }

i m running this code and only one out of the 3 ressources are gone from the provisioning process
terraform fails with Error: timeout - last error: dial tcp 130.61.84.183:22: i/o timeout

Error: timeout - last error: dial tcp 130.61.82.46:22: i/o timeout

Error: timeout - last error: dial tcp 130.61.40.201:22: i/o timeout

Terraform v0.12.6
+ provider.null v2.1.2
+ provider.oci v3.37.0

Your version of Terraform is out of date! The latest version
is 0.12.8. You can update by downloading from www.terraform.io/downloads.html

**Comment by parrneet** [comment] 2019-09-07 00:02
Hi @eugsim1 

Please provide complete tf config that you are using so we can try to reproduce the issue.

**Comment by eugsim1** [comment] 2019-09-07 08:40
On Saturday, September 7, 2019, 2:02:18 AM GMT+2, Parneet Kaur <notifications@github.com> wrote:  
 
 
Hi @eugsim1

Please provide complete tf config that you are using so we can try to reproduce the issue.

**Comment by eugsim1** [comment] 2019-09-09 12:51
Hello i have maild the code but for some reason i dont see the updates, today i had the same issues here is the code, please ping me as i m internal to give you more details :

### main configuration file for the ebs 12  image
###
resource "oci_core_instance" "ebs_instance" {
    count = var.instance_count    
    availability_domain = "${var.availability_domain}"
    compartment_id = "${var.compartment_ocid}"
    shape = "VM.Standard2.2"

     agent_config {
          is_monitoring_disabled = "false"
    }
    create_vnic_details {
        subnet_id = "${var.subnet_id}"
    }
    defined_tags = {}
    display_name = "${var.instance_name}${count.index}"
    extended_metadata = null
    fault_domain = "${var.fault_domain}"
    freeform_tags = {}
    hostname_label = "${var.instance_name}${count.index}"
    ipxe_script = null
    is_pv_encryption_in_transit_enabled = null
    metadata = {
        ssh_authorized_keys = "${var.ssh_authorized_keys}"
        user_data = ""
    }
    source_details {
        source_id = "ocid1.image.oc1..aaaaaaaaa6u4xss6f6vdklc6kji7ifk6addnnmya3kyukpcje46bq737jtvq"
        source_type = "image"
        boot_volume_size_in_gbs = "375"
        kms_key_id = ""
    }
    preserve_boot_volume = false
}


/// this provisioner failed 
resource "null_resource" "cluster" {
  count = var.instance_count
  connection {
    type        = "ssh"
    host        = "${element( flatten(list(oci_core_instance.ebs_instance.*.public_ip)) , count.index)}"
    user        = "opc"
    private_key = "${file("~/.ssh/priv.txt")}"
  }  

    provisioner "file" {
    source      = "init.sh"
    destination = "/tmp/init.sh"
    }
    

    provisioner "file" {
    source      = "ebsdb_apps.xml"
    destination = "/tmp/ebsdb_apps.xml"
    }    

  
  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/init.sh","/tmp/init.sh"
    ]
  }

}

// without the data.
output "ebs-ip" {
  //count = var.instance_count
  value = "${flatten(list(oci_core_instance.ebs_instance.*.public_ip))}"
}

// update the dns record of each ebs instance
resource "oci_dns_record" "record-a-ebs" {
  count = var.instance_count
  zone_name_or_id = "emeacloudpursuit.com"
  domain          = "${var.instance_name}${count.index}.emeacloudpursuit.com"
  rtype           = "A"
  rdata           = "${element( flatten(list(oci_core_instance.ebs_instance.*.public_ip)) , count.index)}"
  ttl             = 3600
}

**Comment by bowfeng** [comment] 2019-09-11 17:50
@eugsim1 
   How do I find you in slack?

**Comment by bowfeng** [comment] 2019-09-16 20:03
close it for now. feel free to contact me directly to follow up this issue.

**Comment by eugsim1** [comment] 2019-09-17 22:29
Hello i m still getting 
Error: timeout - last error: dial tcp 130.61.40.92:22: connect: connection refused

the deployment with terraform at lest seems for me unreliable 

i had this issue twice this is what i m trying to do :

esource "oci_core_instance" "ebs_instance" {
  count               = var.instance_count
  availability_domain = var.availability_domain
  compartment_id      = var.compartment_ocid
  shape               = "VM.Standard2.2"

  agent_config {
    is_monitoring_disabled = "false"
  }
  create_vnic_details {
    subnet_id = var.subnet_id
  }
  defined_tags                        = {}
  display_name                        = "${var.instance_name}${count.index}"
  fault_domain                        = var.fault_domain
  freeform_tags                       = {}
  hostname_label                      = "${var.instance_name}${count.index}"
  metadata = {
    ssh_authorized_keys =  "${trimspace(file("${var.ssh_authorized_keys}"))}"
##   user_data = "${base64encode(file("init.sh"))}"
  }
  

  source_details {
    source_id               = var.source_id
    source_type             = "image"
    boot_volume_size_in_gbs = "375"
    kms_key_id              = ""
  }
  preserve_boot_volume = false
}


### this provisioner failed

resource "null_resource" "init_ebs_sys" {
  count = var.instance_count
  depends_on = [ "oci_core_instance.ebs_instance" ]
  connection {
    type = "ssh"
    host = element(
      flatten([oci_core_instance.ebs_instance.*.public_ip]),
      count.index,
    )
    user        = "opc"
    private_key = "${trimspace(file("${var.private_key}"))}"
  }

  provisioner "file" {
    source      = "init.sh"
    destination = "/tmp/init.sh"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/init.sh",
      "/tmp/init.sh",
    ]
  }
  
 }
  
  
resource "null_resource" "init_cert_sys" {
  count = var.instance_count
  depends_on = [ "null_resource.init_ebs_sys" ]
  connection {
    type = "ssh"
    host = element(
      flatten([oci_core_instance.ebs_instance.*.public_ip]),
      count.index,
    )
    user        = "oracle"
    private_key = "${trimspace(file("${var.private_key}"))}"
  }


if the "null_rssource" fails then terraform provider is having a very big issue

The script fails when the instance_count > 1  , here i m trying with 3 
the servers are created then i m getting these errros

Error: timeout - last error: dial tcp 130.61.40.92:22: i/o timeout


(base) [oracle@localhost ebs3-workshop-deploymentebs12]$ terraform apply
oci_core_instance.ebs_instance[0]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.abtheljs76kegxskpgrs4tipbwdlflzq4gw42wqbffyaftuphf6p7maklvaq]
oci_core_instance.ebs_instance[1]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.abtheljsu3o67uzgbwfyyz2avlqscs5eepucdfns4s2s2jq5fkjetngknzhq]
oci_core_instance.ebs_instance[2]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.abtheljsswoa6pgivwu5ir644pnvpjxglnwyw6cxupmldvzyapohop7f2bkq]
null_resource.init_ebs_sys[0]: Refreshing state... [id=5172699631090037712]
null_resource.init_ebs_sys[1]: Refreshing state... [id=9013286040710803779]
null_resource.init_ebs_sys[2]: Refreshing state... [id=5755520785974696655]
local_file.hosts_per_instance[1]: Refreshing state... [id=1226538b1bd0da597eb6891ba25aecf97bbc1cdd]
local_file.hosts_per_instance[2]: Refreshing state... [id=b85526b1040f5d71294387adba3a4645327c9142]
local_file.hosts: Refreshing state... [id=38c7cf97bba3ae093e54b18d08ffedc0762ebb21]
local_file.hosts_per_instance[0]: Refreshing state... [id=63d620fda51de436c1e9bd00c57baa7a7ddbbdf3]
oci_dns_record.record-a-ebs[1]: Refreshing state... [id=456d0b54e95003e3e069bab96017f89b]
oci_dns_record.record-a-ebs[2]: Refreshing state... [id=bc601ed4a37609e4224c6bace8347aa8]
oci_dns_record.record-a-ebs[0]: Refreshing state... [id=760fa7191a7fe48d76c7df40296661c4]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # null_resource.init_cert_sys[0] will be created
  + resource "null_resource" "init_cert_sys" {
      + id = (known after apply)
    }

  # null_resource.init_cert_sys[1] will be created
  + resource "null_resource" "init_cert_sys" {
      + id = (known after apply)
    }

  # null_resource.init_cert_sys[2] will be created
  + resource "null_resource" "init_cert_sys" {
      + id = (known after apply)
    }

  # null_resource.init_ebs_sys[1] is tainted, so must be replaced
-/+ resource "null_resource" "init_ebs_sys" {
      ~ id = "9013286040710803779" -> (known after apply)
    }

Plan: 4 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.init_ebs_sys[1]: Destroying... [id=9013286040710803779]
null_resource.init_ebs_sys[1]: Destruction complete after 0s
null_resource.init_ebs_sys[1]: Creating...
null_resource.init_ebs_sys[1]: Provisioning with 'file'...
null_resource.init_ebs_sys[1]: Still creating... [10s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [20s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [30s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [40s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [50s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [1m0s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [1m10s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [1m20s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [1m30s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [1m40s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [1m50s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [2m0s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [2m10s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [2m20s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [2m30s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [2m40s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [2m50s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [3m0s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [3m10s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [3m20s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [3m30s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [3m40s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [3m50s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [4m0s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [4m10s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [4m20s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [4m30s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [4m40s elapsed]
null_resource.init_ebs_sys[1]: Still creating... [4m50s elapsed]


Error: timeout - last error: dial tcp 130.61.40.92:22: connect: connection refused

**Comment by bowfeng** [comment] 2019-09-17 23:04
@eugsim1  this null_resource is Terraform's resource, we don't have control of it. However we want to reproduce it and see how we can help u. Can you send me your script? jian.gong@oracle.com. Since you are internal, you can also ping me directly.

**Comment by eugsim1** [comment] 2019-09-18 01:31
i have added the following code 
resource "null_resource" "dont_hurry_up" {
    depends_on = [ "oci_core_instance.ebs_instance" ]
    provisioner "local-exec" {
    command = "sleep 120" # Wait for the instance to be ready 
    
  }
 }

resource "null_resource" "init_ebs_sys" {
  count = var.instance_count
  depends_on = [ "null_resource.dont_hurry_up" ]
  connection {
    type = "ssh"
    host = element(
      flatten([oci_core_instance.ebs_instance.*.public_ip]),
      count.index,
    )
    user        = "opc"
    private_key = "${trimspace(file("${var.private_key}"))}"
  }

  provisioner "file" {
    source      = "init.sh"
    destination = "/tmp/init.sh"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/init.sh",
      "/tmp/init.sh",
    ]
  }
    
 }

resource "null_resource" "init_cert_sys" {
  count = var.instance_count
  depends_on = [ "null_resource.init_ebs_sys" ]
  connection {
    type = "ssh"
    host = element(
      flatten([oci_core_instance.ebs_instance.*.public_ip]),
      count.index,
    )
    user        = "oracle"
    private_key = "${trimspace(file("${var.private_key}"))}"
  }

  provisioner "file" {
    source      = "cert.sh"
    destination = "/tmp/cert.sh"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/cert.sh",
      "/tmp/cert.sh",
    ]
  }  
  
 
}


some times i m getting an execution error on the scripts ...

**Comment by bowfeng** [comment] 2019-09-23 15:52
@eugsim1 can you increase sleep time in `null_resource.dont_hurry_up` to see if it makes difference?

**Closed** 2019-09-23 16:11 UTC
Labels: bug

**Comment by eugsim1** [comment] 2019-09-23 16:14
terraform run time code doenst handle long ruining provisioning scripts neither support during a script execution sudo su ... when the scripts are running with an external tool as ansible are the defaults of terraform are gone.
And the most important ansible execution is sequential no matter the time the script will take to run the task
