### ISSUE TITLE
Data source oci_identity_regions return null for R1

### ISSUE THREAD

**Issue by xuhanshan** [terraform-providers/terraform-provider-oci#1133] opened 2020-07-30 22:32 UTC
### Terraform Version and Provider Version
Terraform v0.12.26. 
provider.oci v3.80.0

### Terraform Configuration Files

```hcl
data "oci_identity_regions" "service_regions" {
}
locals {
  region_abbreviate_mapping = {
    for region in data.oci_identity_regions.service_regions.regions:
    region.name => lower(region.key)
  }
}
```

### Debug Output
So when I ran terraform plan against the tf file in R1, it came across an error

```
Error: Iteration over null value

  on ../service-vcn/main.tf line 15, in locals:
  14: 
  15:   for region in data.oci_identity_regions.service_regions.regions:
  16: 
  17: 
    |----------------
    | data.oci_identity_regions.service_regions.regions is null

A null value cannot be used as the collection in a 'for' expression.

```

### Expected Behavior

there should be error. terraform plan should have run successfully. I was able to run terraform plan against this in R1 on Jul 27.

**Comment by rashik-bhasin** [comment] 2020-07-31 01:46
As discussed with @xuhanshan  , the issue is fixed on his end.

**Closed by rashik-bhasin** 2020-07-31 01:46 UTC
Labels: bug
