### ISSUE TITLE
oci_core_ipsec not allowing null list for 2xBGP tunnels as documented

### ISSUE THREAD

**Issue by icsfot** [terraform-providers/terraform-provider-oci#1110] opened 2020-07-03 14:09 UTC
We want to set up with BGP, so no static routes, according to documentation we can pass an empty list. but to no avail, plan passes the error only occurs during apply phase

TF code 
resource "oci_core_ipsec" "cbsprod_ip_sec_connection" {

  compartment_id = local.comp_ocid
  cpe_id            = oci_core_cpe.cbsprod_cpe.id
  drg_id            = oci_core_drg.cbsprod_drg.id
  static_routes  = [ ]

  display_name = "prod_ipsec"

  freeform_tags = {

    "terraform" = "true"
    "project"   = "CBSProd-VCN-UK_london_1"
  }
}

Produces the following result :-
 Error: Missing required argument
   on ipsec.tf line 1, in resource "oci_core_ipsec" "cbsprod_ip_sec_connection":
    1: resource "oci_core_ipsec" "cbsprod_ip_sec_connection" {
 The argument "static_routes" is required, but no definition was found.
 Plan: failed - please check manually... EXIT

**Comment by parrneet** [comment] 2020-07-06 16:20
Hi @icsfot 

Thank you for reporting this.
It seems like a regression from a previous fix. We will update once this is fixed.

**Comment by afedorch** [comment] 2020-07-06 19:10
Hello @icsfot 

Could you please share full tf configuration and logs to reproduce the problem? (see: https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider) What Terraform version are you using?

The latest change in `oci_core_ipsec` resource allows empty values for `static_routes` on provider side, however, there are still requriments by the service: 
- If you configure both tunnels to use BGP dynamic routing, you can provide an empty list for the static routes
- If you configure at least one tunnel to use static routing, then in the request you must provide at least one valid static route (you're allowed a maximum of 10). For example: 10.0.0.0/16.

Do you get `Service error:MissingParameter. Static routes must be specified..` when configuration has `static_routes` as empty list?

Thanks

**Comment by icsfot** [comment] 2020-07-08 13:45
Hi, 

Thanks for the quick response, to clarify a few missing items, Terraform version = 0.12.28 and Provider 3.83.1.

I've had to set primary route through the webUI to proceed but will confirm the that the BGP tunnels are setup prior to the call of oci_core_ipsec for the backup ipsec.

Will update when I have the opportunity to, once again thanks for your help

**Comment by afedorch** [comment] 2020-07-14 00:29
@icsfot, I will be closing this request for now. Please feel free to submit the scenario to reproduce the problem, thank you!

**Closed by afedorch** 2020-07-14 00:29 UTC
Labels: bug

**Comment by icsfot** [comment] 2020-08-05 16:12
I've just trying to get a backup leg working, still having the same issue

`resource "oci_core_ipsec" "sutton_ipsec_connection" {

  compartment_id = local.comp_ocid
  cpe_id         = oci_core_cpe.primary.id
  drg_id         = oci_core_drg.this.id
  static_routes  = [ ]

  display_name = "prod_ipsec"

  freeform_tags = {

    "terraform" = "true"
    "project"   = "CBSProd-VCN-UK_london_1"
  }
}

data "oci_core_ipsec_connection_tunnels" "cbsprod_ip_sec_connection_sutton_tunnels" {
  ipsec_id = oci_core_ipsec.sutton_ipsec_connection.id
}

resource "oci_core_ipsec_connection_tunnel_management" "sutton_ipsec_connection_tunnel_management_1" {
  ipsec_id  = oci_core_ipsec.sutton_ipsec_connection.id
  tunnel_id = data.oci_core_ipsec_connection_tunnels.cbsprod_ip_sec_connection_sutton_tunnels.ip_sec_connection_tunnels.0.id

  bgp_session_info {
    customer_bgp_asn      = "12345"
    customer_interface_ip = "169.254.2.41/30"
    oracle_interface_ip   = "169.254.2.42/30"
  }

  display_name  = "cbsprod_sutton_t1"
  routing       = "BGP"
}

resource "oci_core_ipsec_connection_tunnel_management" "sutton_ipsec_connection_tunnel_management_2" {
  ipsec_id  = oci_core_ipsec.sutton_ipsec_connection.id
  tunnel_id = data.oci_core_ipsec_connection_tunnels.cbsprod_ip_sec_connection_sutton_tunnels.ip_sec_connection_tunnels.1.id

  bgp_session_info {
    customer_bgp_asn      = "12345"
    customer_interface_ip = "169.254.2.45/30"
    oracle_interface_ip   = "169.254.2.46/30"
  }

  display_name  = "cbsprod_sutton_t2"
  routing       = "BGP"
}
`

 Error: Service error:MissingParameter. Static routes must be specified.. http status code: 400. Opc request id: 9c7cfd445086bb47a22f9051d8af1961/71988C0963401138906643D015148458/AD0A98EE75C3190FF1068CBFEBEF8AA0
   on ipsec.tf line 1, in resource "oci_core_ipsec" "sutton_ipsec_connection":
    1: resource "oci_core_ipsec" "sutton_ipsec_connection" {
 Apply: exit code 1
 -- terraform apply failed, continue to save state in case of partial completion
 done.

**Comment by imrannayer** [comment] 2020-11-19 15:45
Getting following error while creating ipsec connection with empty list passed for `static_routes`

```
oci_core_ipsec.ip_sec_connection: Creating...

Error: Service error:MissingParameter. Static routes must be specified.. http status code: 400.

```

Here is sample code:

```
resource "oci_core_ipsec" "ip_sec_connection" {
  compartment_id = var.compartment_ocid
  display_name   = "${var.prefix}-ipsec"
  cpe_id         = oci_core_cpe.my_cpe.id
  drg_id         = oci_core_drg.drg.id
  static_routes = []
}
```

**Comment by imrannayer** [comment] 2020-11-19 15:48
@afedorch Can you plz reopen this issue as it is still an issue.

**Comment by karthicgit** [comment] 2022-01-04 04:28
@afedorch @varmax2511 Can this issue be reopened ? I am facing the same issue when passing empty static_routes for BGP.  If i pass static_routes = [""] I get the below error 
Error: 400-InvalidParameter 
│ Provider version: 4.57.0, released on 2021-12-15. This provider is 2 version(s) old.  
│ Service: Core Ip Sec Connection 
│ Error Message:  is not a valid ip network. 
│ OPC request ID: e6c00c23cdd9e49824cb9db377352da5/5A1DC76D6DC9A2128668E300399C9D3C/CAFA48D725395C23CE08A8F8B5D6494A 
│ Suggestion: Please Update the parameter(s) in the Terraform config as per error message  is not a valid ip network.

2. When i pass static_routes = [] then the err message is 
Error: 400-MissingParameter 
│ Provider version: 4.57.0, released on 2021-12-15. This provider is 2 version(s) old.  
│ Service: Core Ip Sec Connection 
│ Error Message: Static routes must be specified. 
│ OPC request ID: 760d308ea915ccbbb97fce19007185e7/168E9F5C3BBDA44C1248B6051D75308E/885DACD340D57D1FA5B758E38622F757 
│ Suggestion: Please retry or contact support for help with service: Core Ip Sec Connection.

3 . It seems to be working when i pass static_routes = ["somecidrvalue"]

**Comment by markharding** [comment] 2022-01-14 13:54
Also receiving the same error. 

```
oci_core_ipsec.oci_ip_sec_connection: Creating...
╷
│ Error: 400-MissingParameter 
│ Provider version: 4.59.0, released on 2022-01-12.  
│ Service: Core Ip Sec Connection 
│ Error Message: Static routes must be specified. 
│ OPC request ID: 86d42b1bb89ef14da4e1f5ceca458d5f/CBE189480C2509EEAE74EAB0FCF3CAA8/780E36CC423BDCCD3CBE4816CFB69C66 
│ Suggestion: Please retry or contact support for help with service: Core Ip Sec Connection
│ 
│ 
│   with oci_core_ipsec.oci_ip_sec_connection,
│   on main.tf line 80, in resource "oci_core_ipsec" "oci_ip_sec_connection":
│   80: resource "oci_core_ipsec" "oci_ip_sec_connection" {
│ 
```

```tf
resource "oci_core_ipsec" "oci_ip_sec_connection" {
  compartment_id = var.oci_compartment_ocid
  cpe_id         = oci_core_cpe.oci_cpe.id
  drg_id         = oci_core_drg.oci_drg.id
  static_routes  = [ ]
  display_name   = "oci-to-aws-vpn"
}
```
