### ISSUE TITLE
Can't destroy with VNIC attachment

### ISSUE THREAD

**Issue by daveminer1** [terraform-providers/terraform-provider-oci#663] opened 2018-12-04 23:53 UTC
### Terraform Version

0.11.8

### OCI Provider Version

3.9.0

### Description:
I create a VM instance using a custom image (Solaris) with an extra VNIC attachment on a second subnet in the VCN. This works fine, but then I'm unable to destroy the instance, it hangs for 15 minutes trying to destroy the VNIC attachment and then fails:

Error: Error applying plan:

1 error(s) occurred:

* oci_core_vnic_attachment.vnicattachment1 (destroy): 1 error(s) occurred:

* oci_core_vnic_attachment.vnicattachment1: timeout while waiting for state to become 'DETACHED' (last state: 'DETACHING', timeout: 15m0s)

### Terraform Plan
```hcl
variable "region" {
    default = "us-phoenix-1"
}

variable "compartment_ocid" {
    default = "ocid1.compartment.oc1..aaaaaaaa24peoozehwl6dqfqehnlrsppycxwsmwxg522jk74hrv7carh7m3q"
}

variable "instance_shape" {
    default = "VM.Standard2.1"
}

variable "boot_volume_size" {
    default = "50"
}

variable "instance_availability_domain" {
    default = "oscS:PHX-AD-1"
}

variable "instance_display_name" {
    description = "Hostname for your instance"
}

variable "ssh_public_key_path" {
    description = "Path to ssh public key for access to privileged user 'opc' and console"
}

variable "subnet1_id" {
    default = "ocid1.subnet.oc1.phx.aaaaaaaa3gxaz2gzbibjph7zoslvchr7pn5vhndauv4gkruywdydx6tbd2pa"
}

variable "subnet2_id" {
    default = "ocid1.subnet.oc1.phx.aaaaaaaairmmvjlkvzsbwtushdhjyeaoatuv6op6lukolgbwfp6xepp4llia"
}

variable "image_id" {
    default = "ocid1.image.oc1.phx.aaaaaaaa6kojksmxkfnzy5cevjxooww4qzyy35isioa5yodrbypybht2ruoa"
}

data "oci_core_vnic" "vnic1" {
    #Required
    vnic_id = "${oci_core_vnic_attachment.vnicattachment1.vnic_id}"
}

data "oci_core_private_ips" "vnic1_ips" {
    vnic_id = "${data.oci_core_vnic.vnic1.id}"
}

resource "oci_core_instance" "vm_instance" {
	#Required
	availability_domain = "${var.instance_availability_domain}"
	compartment_id = "${var.compartment_ocid}"
	shape = "${var.instance_shape}"

	#Optional
	create_vnic_details {
		#Required
		subnet_id = "${var.subnet1_id}"
		assign_public_ip = false
	}
	display_name = "${var.instance_display_name}"
	metadata {
		ssh_authorized_keys = "${file(var.ssh_public_key_path)}"
	}
	source_details {
	    #Required
	    source_type = "image"
	    source_id = "${var.image_id}"

	    #Optional
	    boot_volume_size_in_gbs = "${var.boot_volume_size}"
	}
	preserve_boot_volume = false
}

resource "oci_core_instance_console_connection" "vm_instance_console_connection" {
	#Required
	instance_id = "${oci_core_instance.vm_instance.id}"
	public_key = "${file(var.ssh_public_key_path)}"
}

resource "oci_core_vnic_attachment" "vnicattachment1" {
    #Required
    create_vnic_details {
        #Required
        subnet_id = "${var.subnet2_id}"

        #Optional
        assign_public_ip = "false"
    }
    instance_id = "${oci_core_instance.vm_instance.id}"
}

output "InstanceAddress" {
    value = "${oci_core_instance.vm_instance.private_ip}"
}

output "InstanceSecondaryAddress" {
    value = "${lookup(data.oci_core_private_ips.vnic1_ips.private_ips[0], "ip_address")}"
}
```

**Comment by ravitandonrt** [comment] 2018-12-05 00:05
Thanks for reporting @daveminer1, I updated your issue for formatting. We will try to repro the config you provided.

Meanwhile, can you help provide this additional information:
1. Did this used to work before and is just a regression with v3.9.0? Or this is the first time it happened?
2. Since the VNIC state is in 'DETACHING' as you mention and time out occurred on waiting 'DETACHED', did a retry help?

Backdrop on #2 above is that, the default timeout for most operations is 15 minutes (once the request is accepted), if there is an ongoing service issue impacting the said resource, the timeout error may occur. The alternative is to either retry or increase the delete operation timeout in the terraform config using the following syntax:

```hcl
resource "oci_resource" "timeout_example" {
  description    = "oci resource"
  name              = "resource"

  # ...

  timeouts {
    create = "60m"
    delete = "2h"
  }
}
```

**Comment by daveminer1** [comment] 2018-12-05 00:10
It hasn’t worked in any version of the provider. A retry sees the same result. 


Dave

**Comment by ravitandonrt** [comment] 2018-12-06 00:33
**Update:**

- I was able to successfully repro the issue by using the above mentioned Terraform config with few modifications. I was able to search the image to use published by Dave Miner (reporter himself) on his blog at: https://blogs.oracle.com/dminer/getting-started-with-solaris-114-beta-images-for-oracle-cloud-infrastructure
- The issue also occurs when the vnicAttachment is detached from OCI Console (UI) indicating it is a service issue and not a terraform provider issue. I ensured that console and Terraform/go-sdk are using same API service calls.
- Deleting the instance implicitly deletes the vnicAttachments irrespective of their state
- Due to dependency walk, Terraform first always try to destroy the vnicAttachment before other resources, and due to the service issue the resource vnicAttachment always get's stuck in `DETACHING` state and hence OCI Provider for Terraform times out at 15 minutes because the state does not change and does not reach the terminal state of `DETACHED`. Retries do not help as it never recovers. Reference: https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/core_vnic_attachment_resource.go#L228

**Work-around:**

As the vnicAttachments are implicitly deleted when an instance is destroyed, the work-around is to manually remove them from the Terraform state so that Terraform can continue to destroy other resources including the instance that implicitly deletes the failing vnicAttachment.

```
terraform state rm oci_core_vnic_attachment.vnicattachment1
```

Reference: https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/VnicAttachment/DetachVnic

**Closing Notes:**

This issue is not with the OCI provider as the affected resource never reaches a terminal state, hence we will be raising this with service team to further investigate why vnicAttachment fails for Solaris. 

We do have tests targeting this specific resource at https://github.com/terraform-providers/terraform-provider-oci/blob/master/oci/core_vnic_attachment_test.go#L50 , so this could be an issue with the service compatibility with the provided custom image.

**Closed by ravitandonrt** 2018-12-06 00:33 UTC
Labels: investigate
