### ISSUE TITLE
I cannot ssh to the poolinstance . it timed out

### ISSUE THREAD

**Issue by beide** [terraform-providers/terraform-provider-oci#941] opened 2019-12-12 20:53 UTC
instance_pool.tf

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by beide** [comment] 2019-12-12 20:54
after successfully ran the terraform, instance_pool.tf. the pool instance is not accessible via it's public ip.

**Comment by beide** [comment] 2019-12-12 20:54
via ssh. it timed out

**Comment by beide** [comment] 2019-12-12 20:55
if I manually create instance used the image in the script,  ssh instance won't be timed out.

**Comment by beide** [comment] 2019-12-12 21:40
I can also ssh into the testinstanceforinstancepool but not the ones created by the custom image in the pool config.

**Comment by alexng-canuck** [comment] 2019-12-12 22:10
Hi @beide ,
Can you share the full SSH error message?

SSH issues are typically not related to Terraform provider. They are often either caused by:
- network misconfiguration
- SSH key misconfiguration

Can you share the .tf configuration that you used to create the instance pool and networks? Can you also make sure that you have SSH authorized keys configured correctly in your configuration?

**Comment by alexng-canuck** [comment] 2019-12-13 22:32
Closing this issue as it's being taken offline.

**Closed by alexng-canuck** 2019-12-13 22:32 UTC
Labels: bug
