### ISSUE TITLE
Terraform plan crashes in v3.24

### ISSUE THREAD

**Issue by skripted** [terraform-providers/terraform-provider-oci#758] opened 2019-04-27 19:39 UTC
### Terraform Version

<details>
# Run this command to get the terraform version:
$ terraform --version
Terraform v0.11.13
+ provider.oci v3.24.0
</details>

### OCI Provider Version

<details>
# Execute the plugin directly to get the version:

$ \<path-to-plugin\>/terraform-provider-oci
/Users/myuser/work/oci_mytenancy/.terraform/plugins/darwin_amd64
$ ls
lock.json				terraform-provider-oci_v3.24.0_x4
</details>

### Description:
Running the Terraform plan - crashes. 

### Terraform Plan

<details>
A self-contained terraform file that reproduces the issue. If this is not provided, your ticket may be closed.
[crash.log](https://github.com/terraform-providers/terraform-provider-oci/files/3124273/crash.log)

</details>

**Comment by parrneet** [comment] 2019-04-29 17:08
Hi @skripted, Please share the terraform config files for us to replicate the issue.

**Comment by skripted** [comment] 2019-04-29 17:51
There are way too many of them for me to share.  Here's a snippet: 


resource "oci_core_security_list" "custdcnet_fpummtsnetAD3_local_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpummtsnetAD3_local_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.dc_fpummtsnetAD3range}" protocol = "all"}
    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_fpummtsnetAD3_mgmt_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpummtsnetAD3_mgmt_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 22 "min" = 22 } },
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 3389 "min" = 3389 } }
      //{ source = "10.10.0.0/16" protocol = "6" tcp_options {"max" = 22 "min" = 22 } }
    ]//ingress ends
    egress_security_rules = [
    ]//egress ends

}

resource "oci_core_security_list" "custdcnet_fpummtsnetAD3_wad_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpummtsnetAD3_wad_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.VCN-CIDR1}" protocol = "6" tcp_options {"max" = 8050 "min" = 8050 } },
      { source = "${var.NET10}" protocol = "6" tcp_options {"max" = 8050 "min" = 8050 } },
      { source = "${var.dc_hpummtsnetAD3range}" protocol = "6" tcp_options {"max" = 9100 "min" = 8000 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 2049 "min" = 2049 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 111 "min" = 111 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 892 "min" = 892 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 32803 "min" = 32803 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 1521 "min" = 1521 } },
      { source = "${var.NET10}" protocol = "6" tcp_options {"max" = 1521 "min" = 1521 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 9100 "min" = 8000 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 5986 "min" = 5985 } }
    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_fpummtsnetAD3_placeholder_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpummtsnetAD3_placeholder_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
}



resource "oci_core_security_list" "custdcnet_hpummtsnetAD3_local_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpummtsnetAD3_local_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.dc_hpummtsnetAD3range}" protocol = "all"}
    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_hpummtsnetAD3_mgmt_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpummtsnetAD3_mgmt_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 22 "min" = 22 } },
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 3389 "min" = 3389 } }
      //{ source = "10.10.0.0/16" protocol = "6" tcp_options {"max" = 22 "min" = 22 } }
    ]//ingress ends
    egress_security_rules = [
    ]//egress ends

}

resource "oci_core_security_list" "custdcnet_hpummtsnetAD3_wad_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpummtsnetAD3_wad_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.VCN-CIDR1}" protocol = "6" tcp_options {"max" = 8050 "min" = 8050 } },
      { source = "${var.NET10}" protocol = "6" tcp_options {"max" = 8050 "min" = 8050 } },
      { source = "${var.dc_fpummtsnetAD3range}" protocol = "6" tcp_options {"max" = 9100 "min" = 8000 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 2049 "min" = 2049 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 111 "min" = 111 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 892 "min" = 892 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 32803 "min" = 32803 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 1521 "min" = 1521 } },
      { source = "${var.NET10}" protocol = "6" tcp_options {"max" = 1521 "min" = 1521 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 9100 "min" = 8000 } },
      { source = "${var.dc_dmzsubnetAD1range}" protocol = "6" tcp_options {"max" = 5986 "min" = 5985 } }

    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_hpummtsnetAD3_placeholder_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpummtsnetAD3_placeholder_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
}


resource "oci_core_security_list" "custdcnet_fpumdbsnetAD3_local_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpumdbsnetAD3_local_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.dc_fpumdbsnetAD3range}" protocol = "all"}
    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_fpumdbsnetAD3_mgmt_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpumdbsnetAD3_mgmt_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 22 "min" = 22 } },
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 3389 "min" = 3389 } }
    ]//ingress ends
    egress_security_rules = [
    ]//egress ends

}

resource "oci_core_security_list" "custdcnet_fpumdbsnetAD3_wad_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpumdbsnetAD3_wad_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_fpumdbsnetAD3_placeholder_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_fpumdbsnetAD3_placeholder_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
}



resource "oci_core_security_list" "custdcnet_hpumdbsnetAD3_local_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpumdbsnetAD3_local_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.dc_hpumdbsnetAD3range}" protocol = "all"}
    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_hpumdbsnetAD3_mgmt_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpumdbsnetAD3_mgmt_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 22 "min" = 22 } },
      { source = "${var.world_ip}" protocol = "6" tcp_options {"max" = 3389 "min" = 3389 } }
    ]//ingress ends
    egress_security_rules = [
    ]//egress ends

}

resource "oci_core_security_list" "custdcnet_hpumdbsnetAD3_wad_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpumdbsnetAD3_wad_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
    ingress_security_rules = [
    ]//ingress ends
}

resource "oci_core_security_list" "custdcnet_hpumdbsnetAD3_placeholder_seclist" {
    provider = "oci.iad"
    compartment_id = "${oci_identity_compartment.cust-comm-network.id}"
    display_name = "custdcnet_hpumdbsnetAD3_placeholder_seclist"
    vcn_id = "${oci_core_virtual_network.custdcnet.id}"
}

**Comment by codycushing** [comment] 2019-04-30 01:28
Hello, based on the log, the error is related to your ingress_security_rules, specifically tcp_options. I have not been able to reproduce the crash with any variant of the rules you show above, however, I was able to reproduce this in both egress and ingress rules by omitting values for respective tcp/udp options:
```
  ingress_security_rules {
      protocol  = "6"
      source    = "0.0.0.0/0"
    tcp_options {
      // omitting these values results in panic
    }
  }
```
Can you investigate if any such pattern might be present in your configs?

**Comment by codycushing** [comment] 2019-05-01 19:30
Hello, can you please verify that no additional security rules have been added to your security list via other tools (console/cli)? This was the cause of the same issue for another customer: https://github.com/terraform-providers/terraform-provider-oci/issues/759#issuecomment-488329535

**Comment by codycushing** [comment] 2019-05-06 20:07
Closing as dup of 759

**Closed by codycushing** 2019-05-06 20:07 UTC
Labels: bug
