### ISSUE TITLE
How to Reboot a VM using Resource Manager

### ISSUE THREAD

**Issue by amikugup** [terraform-providers/terraform-provider-oci#1268] opened 2021-01-06 06:56 UTC
We have a use case to reboot a newly instantiated OCI VM from within the Terraform configuration files using local-exec provisioner.
I could use both OCI CLI commands and oci-curl shell script without any problem by executing Terraform configuration files with my machine.
But same is not working from OCI Resource manager as the execution environment is different.

Got following error while executing OCI CLI command from resource manager

null_resource.rebootvm: Creating...
null_resource.rebootvm: Provisioning with 'local-exec'...
oci_core_volume.this: Creating...
null_resource.rebootvm(local-exec): Executing: ["/bin/bash" "-c" "oci compute instance --action RESET --instance-id  ocid1.instance.oc1.phx.anyhqljsq5fbg5ac5avu663gijwyn4ooeupp5jxryebmjvog3z5t4bovntwq"]
null_resource.rebootvm (local-exec): INFO 2020/12/30 11:25:34.037670 log.go:102: logger level set to:  3
null_resource.rebootvm (local-exec): --cluster-id is required

Error: Error running command 'oci compute instance --action RESET --instance-id ocid1.instance.oc1.phx.anyhqljsq5fbg5ac5avu663gijwyn4ooeupp5jxryebmjvog3z5t4bovntwq': exit status 1. Output: INFO 2020/12/30 11:25:34.037670 log.go:102: logger level set to:  3
--cluster-id is required

So is there any way to achieve the same from the OCI resource manager, please let us know?

**Comment by zexinwanoci** [comment] 2021-01-07 10:59
Hello, from the context it seems like the problem is not related to terraform itself but rather an orm issue. Can you open a ticket against them and close this one? Thank you.

**Closed** 2021-01-07 17:56 UTC
Labels: responded
