### ISSUE TITLE
WAF Policies: InvalidParameter blockResponseCode when block_action set to SHOW_ERROR_PAGE

### ISSUE THREAD

**Issue by dhoogfr** [terraform-providers/terraform-provider-oci#1012] opened 2020-04-02 17:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
tested with:
```
Terraform v0.12.18
+ provider.oci v3.55.0
```
and
``` 
Terraform v0.12.24
+ provider.oci v3.69.0
```

### Affected Resource(s)

oci_waas_waas_policy

### Terraform Configuration Files

```hcl
dynamic access_rules {
  for_each = length(var.waf_xxxx.geo_fencing) == 0 ? [] : ["a"]
  content {
    action                       = "BLOCK"
    block_action                 = "SHOW_ERROR_PAGE"
    block_error_page_code        = "SHOW_ERROR_PAGE"
    block_error_page_description = "This website is not accessible from your location"
    block_error_page_message     = "This website is not accessible from your geographic location"
    block_response_code          = 403
    bypass_challenges            = []
    name                         = "geo_fencing"
    dynamic criteria {
      iterator = country
      for_each = split(",", var.waf_xxxx_fencing)
      content {
        condition = "COUNTRY_IS_NOT"
        value     = country.value
      }
    }
      }
    }

```

### Expected Behavior

WAF Policy is updated, with the block_action set to SHOW_ERROR_PAGE

### Actual Behavior

Apply directly fails with:

Error: Service error:InvalidParameter. blockResponseCode in body should be greater than or equal to 100. http status code: 400. Opc request id:....

### Steps to Reproduce

* create a WAF policy with the block_action set to SET_RESPONSE_CODE
* change the block_action to SHOW_ERROR_PAGE

### Important Factoids

The change works when using the OCI console.
After refreshing the state, I can see the following for the policy

```hcl
access_rules {
    action                       = "BLOCK"
    block_action                 = "SHOW_ERROR_PAGE"
    block_error_page_code        = "SHOW_ERROR_PAGE"
    block_error_page_description = "This website is not accessible from your location"
    block_error_page_message     = "This website is not accessible from your geographic location"
    block_response_code          = 403
    bypass_challenges            = []
    name                         = "geo_fencing"
```

Removing the block_response_code from the code (as it is not relevant with block_action set to show_error_page) makes no difference

**Comment by dhoogfr** [comment] 2020-04-02 19:54
Looks like the problem is not related to the block_action.
I'm now getting errors on other changes as well. For some the error is on the block_response_code, for others it's on the captchaFooter. Even if these parts are not enabled and not changed

**Comment by parrneet** [comment] 2020-04-06 16:29
Hi @dhoogfr - Please provide the debug logs and a simplified TF config to reproduce the issue. 
To obtain the debug output, see the [Verbose logging for OCI Terraform Provider](https://www.terraform.io/docs/providers/oci/guides/troubleshooting.html#verbose-logging-for-oci-terraform-provider).

Here is the doc for access rules https://docs.cloud.oracle.com/en-us/iaas/api/#/en/waas/20181116/AccessRule/

**Comment by dhoogfr** [comment] 2020-04-07 09:27
Hi @parrneet 

Please find the requested gists below:

* Terraform script: https://gist.github.com/dhoogfr/00978b4df2ce987986a8ca3caf0a405a
* Debug output: https://gist.github.com/dhoogfr/917d6c83406c032c5a99b98280f74876

I removed the other resources from the "s3/PutObject Details" output in the debug gist as they contained no changes and because of security

**Comment by mulpk** [comment] 2020-04-11 00:28
Hi @dhoogfr,

I have tried the TF script shared and below are the observations:
- initializing block_response_code = 0 in the access_rules (action="ALLOW") is causing the Service error:InvalidParameter. blockResponseCode in the body should be greater than or equal to 100
- successfully created WAF policy with access_rules action set to BLOCK & block_action set to SET_RESPONSE_CODE and also updated block_action from SET_RESPONSE_CODE ---> SHOW_ERROR_PAGE without any issue.

```terraform
  ...
  waf_config {
    ...
    access_rules {
      action = "ALLOW"
      block_action = "SET_RESPONSE_CODE"
      block_error_page_code = "Access rules"
      block_error_page_description = "Access blocked by website owner. Please contact support."
      block_error_page_message = "Access to the website is blocked."
      //block_response_code = 0  # causes the Service error:InvalidParameter
      bypass_challenges = []
      name = "whitelisted_ips"
      criteria {
        condition = "IP_IN_LIST"
        is_case_sensitive = false
        value = "${oci_waas_address_list.test_address_list.id}"
      }
    }
    access_rules {
      action                       = "BLOCK"
      block_action                 = "SHOW_ERROR_PAGE"   # Did an update from SET_RESPONSE_CODE ---> SHOW_ERROR_PAGE
      block_error_page_code        = "Access rules"
      block_error_page_description = "This website is not accessible from your location."
      block_error_page_message     = "This website is not accessible from your geographic location."
      block_response_code          = 403
      bypass_challenges            = []
      name                         = "geo_fencing"
      criteria {
        condition         = "COUNTRY_IS_NOT"
        is_case_sensitive = false
        value             = "NL"
      }
      criteria {
        condition         = "COUNTRY_IS_NOT"
        is_case_sensitive = false
        value             = "BE"
      }
    }
  }
...
```

Please refer the documentation for block_response_code https://www.terraform.io/docs/providers/oci/r/waas_waas_policy.html#block_response_code
 
Please remove block_response_code = 0 from your configuration and give it a try.

**Comment by dhoogfr** [comment] 2020-04-11 09:03
Hi,

Removing the block_response_code did not help. I'm still getting the same error.
Note that the inventory already showed the block_response_code with an value of 0.
So at certain point, the value was not checked, when the action was not show_response_code.
Also, I did make changes to this policy in the past without problems, while the same block_response_code was set to 0

Changing the code from 0 to 403, did allow the validation to continue

```
~ block_response_code          = 0 -> 403
```

But then I got the following error
```
Error: Service error:InvalidParameter. captchaFooter in body should be at least 1 chars long. http status code: 400. Opc request id: c26c16f58c74a5aa27e4d3d9f249aea8/2d4c022d9108ce233758c05373e49a97/36dd41e2b9b85e980c67b9e998b54ede

  on waf.tf line 23, in resource "oci_waas_waas_policy" "waf_jobstudentatsamsonite":
  23: resource "oci_waas_waas_policy" "waf_jobstudentatsamsonite" {
```

I changed all occurrences of captcha_footer for this policy, but still received the same response.

Could it be that in that the behavior of the API is changed to be more strict and that this is now giving problems because of default values stored?

**Comment by dhoogfr** [comment] 2020-04-11 13:31
Noticed that the accessrules section now also has captcha attributes.
Setting these allowed the terraform apply to continue:

```
    + captcha_footer               = "whatever"
    + captcha_header               = "whatever"
    + captcha_submit_label         = "whatever"
    + captcha_title                = "whatever"
```

However, these are listed as optional with default values and thus should not give an error when not specified

**Comment by mulpk** [comment] 2020-04-15 03:07
Hi @dhoogfr 

Glad to know that you are able to make changes to the policy.

we couldn't replicate the captcha attributes validation issue at our end. 
-> created a new policy using the TF script(same as the one shared by you) -> https://gist.github.com/mulpk/41593597019e88c3bd4bd62d0698937f
-> made changes to the policy as shown in the logs -> 
https://gist.github.com/mulpk/cd51f38219735fd36b1509469dd407ad

Please run the TF script at your end and share the logs for the captcha validation issue. we will ask the service team to look at it.

**Comment by mulpk** [comment] 2020-04-20 19:49
Closing since there hasn't been a response. Please feel free to reopen if the issue still persists

**Closed by mulpk** 2020-04-20 19:49 UTC
Labels: bug, responded
