### ISSUE TITLE
Creation of oci_identity_policy fails to find newly created dynamic role

### ISSUE THREAD

**Issue by tyskjohan** [terraform-providers/terraform-provider-oci#785] opened 2019-06-06 11:44 UTC
The snippet below fails with this error message:
```
* oci_identity_policy.ansible_policy: Service error:InvalidParameter. The dynamic_group Ansible_elhskyt specified in the policy statement does not exist under current compartment hierarchy.
. http status code: 400. Opc request id: ea80c332c85d06666dff471118125a96/A497FBFC512BD3725F9406E51A0210B5/697AF8BAB3C4C11E145A941A26994EA0
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Run from Resource Manager in Console.
* provider.oci: version = "~> 3.28"

### Affected Resource(s)

- oci_identity_policy
- oci_identity_dynamic_group

### Terraform Configuration Files

```hcl
resource "oci_identity_dynamic_group" "ansible_dynamic_group" {
  compartment_id = "${var.tenancy_ocid}"
  description    = "Ansible dynamic group for ${var.EnvName}"
  matching_rule  = "ALL {instance.id = '${oci_core_instance.Ansible.id}'}"
  name           = "Ansible_${var.EnvName}"
}

resource "oci_identity_policy" "ansible_policy" {
  compartment_id = "${oci_identity_compartment.compartment.id}"
  description    = "Ansible identity policy for ${var.EnvName}"
  name           = "Ansible_${var.EnvName}"

  statements = ["Allow dynamic-group Ansible_${var.EnvName} to read all-resources in compartment ${oci_identity_compartment.compartment.name}"]
}

```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Creation should have succeeded.

### Actual Behavior

Creation failed.

**Comment by varmax2511** [comment] 2019-06-07 02:06
Hi @tyskjohan. I would suggest you to use interpolation syntax when specifying the dynamic group in the `ansible_policy` resource. This will create a resource dependency and terraform will first create the `ansible_dynamic_group` followed by `ansible_policy`

`statements = ["Allow dynamic-group ${oci_identity_dynamic_group.ansible_dynamic_group.name} to read all-resources in compartment ${oci_identity_compartment.compartment.name}"]`

To read more on resource dependencies, refer: https://learn.hashicorp.com/terraform/getting-started/dependencies

If the issue still persists, please share the full debug logs (without sensitive information) for further investigation. To get full debug logs, use 
`export TF_LOG=DEBUG`
`export OCI_GO_SDK_DEBUG=1`

**Comment by varmax2511** [comment] 2019-06-10 20:26
Hi @tyskjohan, please let us know if the issue is resolved?

**Comment by tyskjohan** [comment] 2019-06-11 06:34
Haven't gotten there yet, but it seems this problem is inconsistent. The same code that fails on one stack in one tenancy, works fine on a different tenancy.

**Comment by afedorch** [comment] 2019-06-11 17:50
@tyskjohan  do you see inconsistent behavior with the fix suggested by @varmax2511 ? Could you share the logs for the failure? thanks!

**Comment by afedorch** [comment] 2019-06-14 15:56
@tyskjohan  I am closing the issue, the suggested configuration fix should solve the dependency problem. Please, feel free to reopen if the issue persists. Thanks!

**Closed by afedorch** 2019-06-14 15:56 UTC
Labels: bug
