### ISSUE TITLE
wrong results on data "oci_datacatalog_catalogs" "catalogs" 

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1131] opened 2020-07-29 18:45 UTC
the api data "oci_datacatalog_catalogs" "catalogs"  either with the state or the filter map set to active returns ALL the compartements no matter if there is a datacatalog pleas correct asap the provider 

data "oci_datacatalog_catalogs" "catalogs" {
  count          = (var.report_catalogs == true) ? "${length(var.tenancy_compartments_id)}" : 0
  compartment_id = "${var.tenancy_compartments_id[count.index]}"
  state = "ACTIVE"
  /*
  filter {
    name   = "state"
    values = ["ACTIVE"]
  }
   
}

the results are from my teanancy :
{
    "catalogs" = []
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaarbtrtpttu4j4ju76a7qtstxgpzvqithwdsoniim7oahmt4slupba"
    "id" = "2020-07-29 18:31:06.183877741 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "catalogs" = []
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaaw525xduqwo5psovhbqtby6ggdwpoajut7xeqmsgyoogrjoxfxdma"
    "id" = "2020-07-29 18:31:07.340353027 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "catalogs" = []
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaammhfytejwkj7md7lhe2is4yzooh33zdrnyncmoh6ulpse2v2oqaq"
    "id" = "2020-07-29 18:31:07.617347927 +0000 UTC"
    "state" = "ACTIVE"
  },
  {
    "catalogs" = [
      {
        "attached_catalog_private_endpoints" = []
        "compartment_id" = "ocid1.compartment.oc1..aaaaaaaavb7wbs7v5naofrzd6qinqvxxuicxmbbiktofwbrquo7afr3kqqyq"
        "defined_tags" = {
          "Mandatory_Tag.CreateDate" = "2020-02-25T07:50:54.848Z"
          "Mandatory_Tag.CreatedBy" = "ocid1.saml2idp.oc1..aaaaaaaaofk4hczswo3eewraxwcmldcilwhrkvv6ajgn4lgk5wqfb7wafcsa/said.nechab@oracle.com"
        }
        "display_name" = "SWATDataCatalog"
        "freeform_tags" = {}
        "id" = "ocid1.datacatalog.oc1.eu-frankfurt-1.aaaaaaaaj7i4mfnpyvcsggonyojm6dpd6tgd75glukannjgmhxy2genffawq"
        "lifecycle_details" = "Catalog Created"
        "number_of_objects" = 0
        "service_api_url" = ""
        "service_console_url" = ""
        "state" = "ACTIVE"
        "time_created" = "2020-02-25 07:50:56.5 +0000 UTC"
        "time_updated" = "2020-02-25 07:50:56.5 +0000 UTC"
      },
    ]
    "compartment_id" = "ocid1.compartment.oc1..aaaaaaaavb7wbs7v5naofrzd6qinqvxxuicxmbbiktofwbrquo7afr3kqqyq"
    "id" = "2020-07-29 18:31:06.479666851 +0000 UTC"
    "state" = "ACTIVE"
  },

**Comment by rashik-bhasin** [comment] 2020-07-30 18:03
Hi @eugsim1 , 
Thanks for the question.
This is the expected behavior of terraform. Data source works in this fashion only.
 `data "oci_datacatalog_catalogs" "catalogs" {
count = (var.report_catalogs == true) ? "${length(var.tenancy_compartments_id)}" : 0
compartment_id = "${var.tenancy_compartments_id[count.index]}"
state = "ACTIVE"
/*
filter {
name = "state"
values = ["ACTIVE"]
}
}`
Here you are trying to lookup every compartment with the filter `ACTIVE`. Now each lookup will show you the ACTIVE catalogs and when there are no ACTIVE catalogs the data source will show you an empty list(there is no way for you to know if there were any non-active gateways or not when the list is empty []). 
So this is not a bug but the expected behavior as that's the way data source works on terraform end.

Please close the ticket if this answers your question.
Thanks!

**Comment by eugsim1** [comment] 2020-07-30 18:45
Hi 
I dont agree with the "expected" behavior i wanted to use this API to get ALL catalogs which are active and the API  is generating a huge list of empty catalogs i cant get out from terraform the compartements which have ACTIVE catalogs = > only 2.
If the state is ACTIVE = > then an entry should by returned 
If there is no catalog = > state is INACTIVE or whatever there should not be an element with and empty catalog[] 
What is the purpose to have an catalog[]  ?

I cant APPLY the flatten because the list is having elements with catalog [] .
The API call on the compartments when you setup the flag to ACTIVE is giving you a list and you can apply flatten to get everything in a clean way.
In my use case scenario who should i use the API to get ONLY the compartments with deployed catalogs ?
How should i avoid this :
{
"catalogs" = []
"compartment_id" = "ocid1.compartment.oc1..aaaaaaaaw525xduqwo5psovhbqtby6ggdwpoajut7xeqmsgyoogrjoxfxdma"
"id" = "2020-07-29 18:31:07.340353027 +0000 UTC"
"state" = "ACTIVE"
},
{
"catalogs" = []
"compartment_id" = "ocid1.compartment.oc1..aaaaaaaammhfytejwkj7md7lhe2is4yzooh33zdrnyncmoh6ulpse2v2oqaq"
"id" = "2020-07-29 18:31:07.617347927 +0000 UTC"
"state" = "ACTIVE"

**Comment by eugsim1** [comment] 2020-07-30 18:53
Hello can you please revert this to BUG
I dont agree with this hasty explanation the docs are stating clearly this :
state - (Optional) A filter to return only resources that match the specified lifecycle state. The value is case insensitive. 
and the resultats are wrong

**Comment by rashik-bhasin** [comment] 2020-07-30 19:40
As discussed with @eugsim1 on call, closing the issue as this is the expected behavior.

**Closed by rashik-bhasin** 2020-07-30 19:40 UTC
Labels: question
