### ISSUE TITLE
Route to Private Ip cycle error

### ISSUE THREAD

**Issue by schmidtp0740** [terraform-providers/terraform-provider-oci#578] opened 2018-08-24 18:18 UTC
### Terraform Version

<details>
Terraform v0.11.7
</details>

### OCI Provider Version

<details>
terraform-provider-oci 2.1.16

</details>

### Description:
Attempting to create a subnet with a route table that has a route rule to an instance in that subnet. Getting a cycle error when attempting to do so. Seems like you should be able to create the route table and subnet and then create the instance. Then create a route rule to that private ip address.

### Terraform Plan

```
resource "oci_core_route_table" "route_table_for_prod" {
  compartment_id = "${var.compartment_ocid}"
  vcn_id         = "${oci_core_vcn.prod_vcn.id}"
  display_name   = "Route Table For Prod"

  route_rules {
    cidr_block        = "0.0.0.0/0"
    network_entity_id = "${oci_core_internet_gateway.gateway.id}"
  }

  route_rules {
    cidr_block        = "192.168.1.0/24"
    network_entity_id = "${oci_core_private_ip.prod_private_ip.id}"
  }

}

resource "oci_core_instance" "ProdInstanceA" {
  availability_domain = "${lookup(data.oci_identity_availability_domains.ADs.availability_domains[0],"name")}"
  compartment_id      = "${var.compartment_ocid}"
  display_name        = "ProdInstanceA"
  shape               = "${var.InstanceShape}"

  create_vnic_details {
    subnet_id        = "${oci_core_subnet.subnet_a.id}"
    display_name     = "primaryvnic"
    assign_public_ip = true
  }

  source_details {
    source_type = "image"
    source_id   = "${var.InstanceImageOCID[var.region]}"
  }

  metadata {
    ssh_authorized_keys = "${var.ssh_public_key}"
  }

  timeouts {
    create = "60m"
  }
}

resource "oci_core_vnic_attachment" "test_vnic_attachment" {
	#Required
	create_vnic_details {
		#Required
		subnet_id = "${oci_core_subnet.subnet_a.id}"

		#Optional
		private_ip = "192.168.10.5"
	}
	instance_id = "${oci_core_instance.ProdInstanceA.id}"

	#Optional
	display_name = "prodinstancea"
}

resource "oci_core_private_ip" "prod_private_ip" {
  vnic_id      = "${oci_core_vnic_attachment.test_vnic_attachment.vnic_id}"
  display_name = "prodinstanceprivateip"
}
```

while getting the following error:
```
* Cycle: oci_core_subnet.subnet_a, oci_core_instance.ProdInstanceA, oci_core_vnic_attachment.test_vnic_attachment, oci_core_private_ip.prod_private_ip, oci_core_route_table.route_table_for_prod

```

**Comment by alexng-canuck** [comment] 2018-09-28 21:18
Hello @schmidtp0740 
The enhancement to improve this behavior is tracked in issue #270

We will close this as a duplicate of #270.

If you're still seeing issues even after trying @rcohenma 's suggested workaround, please reopen this issue.

Thanks.

**Closed by alexng-canuck** 2018-09-28 21:18 UTC
Labels: question, resolved
