### ISSUE TITLE
imported "connected" lpgs need to be recreated 

### ISSUE THREAD

**Issue by ryanpodonnell1** [terraform-providers/terraform-provider-oci#1345] opened 2021-04-09 15:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

OCI 4.21.0 
Terraform 0.14.2

### Affected Resource(s)

oci_core_local_peering_gateway

### Terraform Configuration Files

```hcl
resource "oci_core_local_peering_gateway" "these" {
  for_each       = local.hub_lpgs
  compartment_id = var.COMPARTMENT_OCID
  vcn_id         = var.firewall_shared_config.vcn
  display_name   = each.key
  peer_id        = each.value.peer_id
  route_table_id = each.value.route_table_id
}
```

### Plan Output
```
# oci_core_local_peering_gateway.these["prd-hub-shd-lpg"] must be replaced
-/+ resource "oci_core_local_peering_gateway" "these" {
      ~ defined_tags                 = {
          - "Oracle-Tags.CreatedBy" = "<REDACTED>"
          - "Oracle-Tags.CreatedOn" = "2021-04-07T20:23:51.523Z"
          - "tgrc.AppEnvironment"   = "Prod"
        } -> (known after apply)
      ~ display_name                 = "prd-hub-shr-lpg" -> "prd-hub-shd-lpg"
      ~ freeform_tags                = {} -> (known after apply)
      ~ id                           = "<REDACTED:current_ocid>" -> (known after apply)
      ~ is_cross_tenancy_peering     = false -> (known after apply)
      ~ peer_advertised_cidr         = "<REDACTED:advertised_IP>" -> (known after apply)
      ~ peer_advertised_cidr_details = [
          - "<REDACTED:advertised_IP>",
        ] -> (known after apply)
      + peer_id                      = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaap6srdyj4swvvivoedja3qio2ckjocffzvzsdblfoimrftsjoowaq" # forces replacement
      ~ peering_status               = "PEERED" -> (known after apply)
      ~ peering_status_details       = "Connected to a peer." -> (known after apply)
      ~ state                        = "AVAILABLE" -> (known after apply)
      ~ time_created                 = "2021-04-07 20:23:51.547 +0000 UTC" -> (known after apply)
        # (3 unchanged attributes hidden)

```

### Expected Behavior

Once terraform resource is imported, it should not need to be recreated.

### Actual Behavior

According to the terraform plan it adds a "peer_id" which forces a replacement defeating the whole purpose of importing

here:
`      + peer_id                      = "ocid1.localpeeringgateway.oc1.iad.aaaaaaaap6srdyj4swvvivoedja3qio2ckjocffzvzsdblfoimrftsjoowaq" # forces replacement` 

### Steps to Reproduce

1. Create an LPG peer between two vcns in the console manually
2. Ensure that LPGs are in a "PEERED" status
3. Import an LPG to terraform state
4. Run terraform apply

### Important Factoids

1. Peer LPGs are in separate state files. I don't believe this has any bearing since subsequent applies after recreating the LPG works just fine but thought I would mention this

**Comment by varmax2511** [comment] 2021-04-09 16:16
Hi @ryanpodonnell1 -- thanks for reaching out. This is a known limitation as the upstream service doesn't return the `peer_id` as part of GET response. Hence importing the LPG doesn't set the `peer_id` in state file. Since `peer_id` is a `forceNew` parameter, it being present in the config triggers a recreation.
For now, the workaround is to manually add the `peer_id` in the state file upon import. We have raised the ticket on the upstream service and are waiting for a response.

**Comment by varmax2511** [comment] 2021-04-09 16:49
Closing this issue as a duplicate of https://github.com/terraform-providers/terraform-provider-oci/issues/1081

**Closed by varmax2511** 2021-04-09 16:49 UTC
Labels: bug, core, responded

**Comment by ryanpodonnell1** [comment] 2021-04-09 17:05
@varmax2511 ouch alright. Thanks for updating the issue
