### ISSUE TITLE
Issue with backup policy assignment

### ISSUE THREAD

**Issue by shruthi2703** [terraform-providers/terraform-provider-oci#1195] opened 2020-10-06 19:53 UTC
Hi Team,

Here is a scenario:
1. Create a Custom Policy via console (Manually) and attach to a block volume.
2. Create the tf files for the same and synch the state using import commands. (Block Volume Policy Attachment is synched)
3. Change the policy assigment from that of custom to 'gold' or 'silver' or ' bronze'.
4. Modify the tf file for policy assignment to the block volume accordingly and import the state.

Issue: Indicates Recreation 

Expected output: That the state is in synch.

We would like to know what can possible be going wrong here? Why does it show as its gonna create it while the data is just supposed to be synched? We have also ran the import stmt for the same.

Output - 

 # oci_core_volume_backup_policy_assignment.RUCHITEST-1_bkupPolicy will be created
  + resource "oci_core_volume_backup_policy_assignment" "RUCHITEST-1_bkupPolicy" {
      + asset_id     = "ocid1.bootvolume.oc1................................cq55sa"
      + id           = (known after apply)
      + policy_id    = "ocid1.volumebackuppolicy.oc1......................................................................6ctew7e54ja"
      + time_created = (known after apply)
    }

  # oci_core_volume_backup_policy_assignment.ruchitest-1_bkupPolicy will be created
  + resource "oci_core_volume_backup_policy_assignment" "ruchitest-1_bkupPolicy" {
      + asset_id     = "ocid1.volume.oc1....................................................................inctq"
      + id           = (known after apply)
      + policy_id    = "ocid1.volumebackuppolicy.oc1............................................uvda"
      + time_created = (known after apply)
    }

TF Files -

```
resource "oci_core_volume_backup_policy_assignment" "ruchitest-1_bkupPolicy" {
    #Required
    asset_id = oci_core_volume.ruchitest-1.id
    policy_id = data.oci_core_volume_backup_policies.block_phxcustompolicy.volume_backup_policies.0.id

}

resource "oci_core_volume_backup_policy_assignment" "RUCHITEST-1_bkupPolicy" {
    #Required
    asset_id = oci_core_instance.RUCHITEST-1.boot_volume_id
    policy_id = data.oci_core_volume_backup_policies.boot_silver.volume_backup_policies.0.id

}


```

**Comment by rashik-bhasin** [comment] 2020-10-06 19:58
Duplicate of https://github.com/terraform-providers/terraform-provider-oci/issues/1194 .

**Closed by rashik-bhasin** 2020-10-06 19:58 UTC
Labels: duplicate, question
