### ISSUE TITLE
seclist issue with icmp option in - provider "terraform-provider-oci_v3.28.1"

### ISSUE THREAD

**Issue by jojolee-us** [terraform-providers/terraform-provider-oci#788] opened 2019-06-07 22:15 UTC
Iam getting this below error

Error: Missing key/value separator

  on .terraform/modules/networking-phx-1/network.tf line 142, in resource "oci_core_security_list" "Networks-corpprodss-ldap-Seclist":
 139: 
 140: 
 141: 
 142:             icmp_options {

Expected an equals sign ("=") to mark the beginning of the attribute value.

Error: Missing key/value separator

  on .terraform/modules/networking-phx/network.tf line 522, in resource "oci_core_security_list" "networks-corpprod1-db-pub-seclist":
 519: 
 520: 
 521: 
 522:             icmp_options {

Expected an equals sign ("=") to mark the beginning of the attribute value.

[@peo-docker phx]$ 

=================

This is the config I have  , This was working yesterday !! Is there any known issue ?

    egress_security_rules = [
         {
            protocol = "${ var.proto_number_icmp }"
            destination = "0.0.0.0/0"
            icmp_options {
                "type" = "8"
             }
         },

**Comment by alexng-canuck** [comment] 2019-06-07 22:19
@jojolee-us 

Did you happen to switch from Terraform v0.11 to Terraform v0.12 recently? Terraform v0.12 introduces breaking changes to Terraform configuration syntax.

For example:
```
egress_security_rules = [
     {
        protocol = "${ var.proto_number_icmp }"
        destination = "0.0.0.0/0"
        icmp_options {
            "type" = "8"
         }
     },
```
should now be

```
egress_security_rules {
        protocol = "${ var.proto_number_icmp }"
        destination = "0.0.0.0/0"
        icmp_options {
            type = "8"
        }
},
```

Notice how the `type` no longer has quotes around it and how the `egress_security_rules` is no longer wrapped within a `[ ]` block.

Highly recommend that you read this guide on dealing with syntax issues while using Terraform v0.12:
https://www.terraform.io/docs/providers/oci/guides/terraform_version_12_upgrade.html#upgrading-terraform-configurations

**Comment by rramge** [comment] 2019-06-10 08:39
Hi,

I think I tracked it down and I am quite sure the root cause is related to Terraform, not the oci provider.

My findings tell me that it's indeed related to quotes - but not in the actual lines which are mentioned in the error message. Instead, it happens here with every occurence of icmp_options{} if there arfe quotes in a different line which is processed earlier, e.g. in a different .tf file. 

Long story short: I think Terraform is the culprit, not the provider.

**Comment by varmax2511** [comment] 2019-06-10 20:22
Hi @rramge , based on above, closing this ticket. Please feel free to reopen if the issue persists.

**Closed by varmax2511** 2019-06-10 20:22 UTC
Labels: question
