### ISSUE TITLE
oci_database_db_home for container database creation shows error message for other existing container database : Service error:NotAuthenticated

### ISSUE THREAD

**Issue by kshinkr** [terraform-providers/terraform-provider-oci#901] opened 2019-10-11 02:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

* provider.external: version = "~> 1.2"
--
  |   | * provider.local: version = "~> 1.3"
  |   | * provider.null: version = "~> 2.1"
  |   | * provider.oci: version = "~> 3.38"
  |   | * provider.template: version = "~> 2.1"
  |   | * provider.tls: version = "~> 2.1"

### Affected Resource(s)

oci_database_db_home (for new container database on exadata)

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Debug Output

Error: Error refreshing state: 5 error(s) occurred:
--
  |   |  
  |   | * module.exadata-database.oci_database_db_home.MARVLPRD: 1 error(s) occurred:
  |   |  
  |   | * module.exadata-database.oci_database_db_home.MARVLPRD: oci_database_db_home.MARVLPRD: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: 9cc0296e971844b0fcfdc7b4854a5c34/7E7256EA3B2CE100C57EF117B3B40A3A/DA1A3226B9A9165B94A88AFC4D889282
  |   | * module.exadata-database.oci_database_db_home.PDRCAU: 1 error(s) occurred:
  |   |  
  |   | * module.exadata-database.oci_database_db_home.PDRCAU: oci_database_db_home.PDRCAU: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: c4189b5c2d5e1e31d5a69b630be3ce6f/0DB8C626A1DA034098F67EFB2EFA8FF5/A5C6021300EB55E2BEEEE395E2FB1BD7
  |   | * module.exadata-database.oci_database_db_system.EXAIADPADR02: 1 error(s) occurred:
  |   |  
  |   | * module.exadata-database.oci_database_db_system.EXAIADPADR02: oci_database_db_system.EXAIADPADR02: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: ab0ddae39a8f889003d9e3efd85c2a74/526E1289EAC500FC008CAA2EB0FA39FA/73761325BB67BB4BE217A2468BD326B6
  |   | * module.exadata-database.oci_database_db_home.CCPCAU: 1 error(s) occurred:
  |   |  
  |   | * module.exadata-database.oci_database_db_home.CCPCAU: oci_database_db_home.CCPCAU: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: 66a2f707636a4d2f54830e3279173a2b/4690DE49658F9EF2E1EF19F50A14FB61/5E9AD2921343E929D6ED2A12E6960B7C
  |   | * module.exadata-database.oci_database_db_home.APXCAU: 1 error(s) occurred:
  |   |  
  |   | * module.exadata-database.oci_database_db_home.APXCAU: oci_database_db_home.APXCAU: Service error:NotAuthenticated. The required information to complete authentication was not provided or was incorrect.. http status code: 401. Opc request id: 12c906f3130885008d9eb0bdafa9c684/370F0CE44212855614667C741ED1F0AB/A04E7CBC78C111DD11068A484EB979C4

Github Gist: https://gist.github.com/
--->

### Expected Behavior

It is supposed to be passed "init" process but it failed out with error message about other existing resources in same directory.

### Actual Behavior

When I tried to run individual new CDB creation is working fine but init process is not working properly then it makes user confused about new CDB creation.

### Steps to Reproduce

Always got into error message when  init process.

**Comment by kshinkr** [comment] 2019-10-11 04:38
Hi
Terraform init process failed due to "Authentification error" but actual apply using only that resource name then it is working fine.

I don't see this kind of error on other resource provisioning.
Jerry

**Comment by afedorch** [comment] 2019-10-12 01:40
Hello @kshinkr!

Thanks for reporting the problem. 
Could you please add information for the `Terraform Configuration Files` section? 

The reason of the NotAuthenticated Service error could be wrong values for the provider configuration: 
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/database/db_systems/db_exadata/provider.tf

Please check if the exdata configuration example could be helpful for your case:
https://github.com/terraform-providers/terraform-provider-oci/blob/master/examples/database/db_systems/db_exadata/resources.tf

thanks!

**Comment by kshinkr** [comment] 2019-10-12 02:07
Thank you for the update.
It doesn’t seem like configuration issue here.

Let me explain more about our environment.

What we are trying to do is creating CDB on existing Exadata machine using oci_database_db_home.

We have created couple of CDBs and this notauthentificated error happening only for existing CDBs. Actual apply for that specific resource is working fine, it is complaining when we run plan and scan all resource tf files under that module directory.

I can give you the configuration but provider information is correct.
We have Rundeck to run terraform...

Jerry

**Comment by afedorch** [comment] 2019-10-13 01:29
@kshinkr 
do you mean that you are able to create the infrastructure with the configuration (`apply` command is working fine) but the subsequent `plan` command fails for the same configuration? 

Could you please share the subset of the configuration with the `oci_database_db_home` resource that reproduces the problem? thanks!

**Comment by kshinkr** [comment] 2019-10-14 02:58
Hi 
Let me give you my tf for oci_database_db_home

// Copyright (c) 2017, 2019, Oracle and/or its affiliates. All rights reserved.

data "external" "APXCAP" {
  program = ["jq", ".", "${path.module}/testdb.json"]
  query   = {}
}

resource "oci_database_db_home" "testdb" {
  db_system_id = "${data.external.testdb.result["db_system_id"]}"

  database {
    admin_password = "${data.external.testdb.result["db_admin_password"]}"
    db_name        = "${data.external.testdb.result["db_name"]}"
    character_set  = "${data.external.testdb.result["character_set"]}"
    ncharacter_set = "${data.external.testdb.result["n_character_set"]}"
    db_workload    = "${data.external.testdb.result["db_workload"]}"
    pdb_name       = "${data.external.testdb.result["pdb_name"]}"

    db_backup_config {
      auto_backup_enabled     = true
      recovery_window_in_days = 30
    }

   defined_tags = {
...
...

                 }
  }

    db_version   = "${data.external.testdb.result["db_version"]}"
    display_name = "${data.external.testdb.result["db_home_display_name"]}"
}
With this TF file 
We can deploy CDB on top of exadata db system but plan/init complaining about other resoutces which already created before and working fine.

We are using .json file as external data input source.

Cheers

**Comment by kshinkr** [comment] 2019-10-14 23:26
Any thought? 
What I suspecting is that oci_database_db_home depends on db_system_id especially exadata db_system, so I am wondering why this module is getting this error, which is not actual error but make users confused.

**Comment by bowfeng** [comment] 2019-10-15 17:03
@kshinkr 
Can you provide me a workable tf script that I can run on my side to reproduce this issue?

**Comment by bowfeng** [comment] 2019-10-22 00:19
@kshinkr 
just want to follow up with you about the tf configuration that we can use to reproduce the issue.

**Comment by bowfeng** [comment] 2019-10-23 16:51
close it for now, and feel free to reopen it.

**Closed by bowfeng** 2019-10-23 16:51 UTC
Labels: bug
