### ISSUE TITLE
cant upload binary files like .zip correctly to object storage

### ISSUE THREAD

**Issue by eugsim1** [terraform-providers/terraform-provider-oci#1098] opened 2020-06-24 11:54 UTC
Hello
From a terraform script i m able to create / download zip files to the localfile system.
As an example : download the wallet of an autonomous db , or use the zip provider of terraform to zip generated files from my scripts

When i try to upload these "binary" zip files with terraform,  to object storage, i have to run a conversion (content64) and then i see the file uploaded to the oci bucket.

The goal is to let a final user download this zip file and use the content.

Unfortunately the zip file has "extra characters" or maybe wrong conversion and i cant open it with the browser.

I can download the file , and if i  run : base64 -d "file_from_object_storage.zip" > file.zip,  then i m getting a correct zip file.

Below is the code to reproduce the issue.

I have used other terraform encoding function but the result is the same.
Am i missing something ?

I had a previous scenario  => upload to object storage through a function, i used the go sdk to upload the file and everything was fine, 

data "oci_objectstorage_namespace" "test_namespace" {
    #Optional
    compartment_id = "${var.compartment_ocid}"
}
data "local_file" "foo" {
    filename = "${path.module}/Wallet_datasf0.zip"
}
resource "oci_objectstorage_object" "test_object" {
    #Required
    bucket = "debug_function"
    content = data.local_file.foo.content_base64 ### maybe here is an issue ?
    namespace = data.oci_objectstorage_namespace.test_namespace.namespace
    object = "Wallet_datasf0.zip"
}
data "oci_objectstorage_object" "Wallet_datasf0" {
    depends_on = [ oci_objectstorage_object.test_object ]
    #Required
    bucket = "debug_function"
    namespace = data.oci_objectstorage_namespace.test_namespace.namespace
    object = "Wallet_datasf0.zip" ###"Wallet_datasf0.zip"
	base64_encode_content = true    #Optional
    #version_id = "${oci_objectstorage_version.test_version.id}"
}
resource "local_file" "Wallet_datasf0-dwl" {
    content_base64= data.oci_objectstorage_object.Wallet_datasf0.content
    filename = "Wallet_datasf0-dwl.zip"
}

**Comment by srishtipmishra** [comment] 2020-06-24 16:35
Hi @eugsim1 Following up from terraform slack channel. Using "source" instead of "content" for zip file path seems to have resolved your issue. Please confirm.

**Comment by eugsim1** [comment] 2020-06-25 08:43
Hello
Yes using source instead of content works, but the documentation has to be more explicit on all parameters, nothing is explained why there are "optional" and other entries  ....can you please make this update to the docs ?

**Comment by srishtipmishra** [comment] 2020-06-25 18:41
@eugsim1 - Yes. Couple of things to shed some light.
source field is used for mutipart uploads useful for large objects. If a part of file fails to upload it can resume from there instead of uploading everything again. 
content field is optional. We'll update the docs to reflect this. 
I am closing this ticket since the issue is resolved.

**Closed by srishtipmishra** 2020-06-25 18:41 UTC
Labels: bug, responded

**Comment by eugsim1** [comment] 2020-06-25 19:49
thanks for the clarification but still the documentation has to be clear and updated to describe EXACTLY this feature from the call description i see this :
source - (Optional) An absolute path to a file on the local system. Cannot be defined if content or source_uri_details is defined. 

I m not a fortune teller to start to make guesses why an "absolute path"  is translated to mutlipart uploads How a "normal" user could guess this ? Either you create clear examples either we will spend ages to discover the obvious facts ...
