### ISSUE TITLE
Error: Provider produced inconsistent final plan while storing an object in the bucket

### ISSUE THREAD

**Issue by chandrashekhar-linux** [terraform-providers/terraform-provider-oci#1228] opened 2020-11-11 03:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/oci v4.1.0

### Affected Resource(s)

oci_objectstorage_object

### Terraform Configuration Files

```
data "oci_objectstorage_namespace" "ns" {
   compartment_id = var.compartment_ocid
}

resource "oci_core_instance" "oci_instance" {
  availability_domain = var.ad
  compartment_id      = var.compartment_ocid
  display_name        = "test-instance"
  shape               = var.instance_shape

  create_vnic_details {
    subnet_id        = var.subnetid
    display_name     = "primarynic"
    assign_public_ip = true
    hostname_label   = "testinstance"
  }

  source_details {
    source_type = "image"
    source_id   = var.image_ocid[var.region]
  }


  metadata = {
    ssh_authorized_keys = file(var.ssh_public_key)
  }

  timeouts {
    create = "60m"
  }

  provisioner "local-exec" {
    command = "rm metadata.txt"
  }
}

resource "null_resource" "oci_metadata" {
  provisioner "local-exec" {
    command = "echo ${oci_core_instance.oci_instance.private_ip} >> metadata.txt"
  }
}

resource "oci_objectstorage_object" "metadata" {
  depends_on          = [null_resource.oci_metadata]
  namespace           = data.oci_objectstorage_namespace.ns.namespace
  bucket              = var.bucket_name
  object              = "metadata"
  content_language    = "en-US"
  content_type        = "text"
  content             = file("metadata.txt")
  content_disposition = "attachment; filename=\"metadata.txt\""
}

output private_ip {
  value = oci_core_instance.oci_instance.private_ip
}

```
### Expected Behavior

upload a object to the bucket specified, even if it is being updated by templates itself.

### Actual Behavior

data.oci_objectstorage_namespace.ns: Refreshing state...
oci_core_instance.oci_instance: Creating...
oci_core_instance.oci_instance: Still creating... [10s elapsed]
oci_core_instance.oci_instance: Still creating... [20s elapsed]
oci_core_instance.oci_instance: Still creating... [30s elapsed]
oci_core_instance.oci_instance: Still creating... [40s elapsed]
oci_core_instance.oci_instance: Still creating... [50s elapsed]
oci_core_instance.oci_instance: Still creating... [1m0s elapsed]
oci_core_instance.oci_instance: Still creating... [1m10s elapsed]
oci_core_instance.oci_instance: Provisioning with 'local-exec'...
**oci_core_instance.oci_instance (local-exec): Executing: ["/bin/sh" "-c" "rm metadata.txt"]**
oci_core_instance.oci_instance: Creation complete after 1m12s [id=ocid1.instance.oc1.phx.anyhqljsq5fbg5acfxjyjctrmugjkyb
tmfo2bbzplfn32iulj47lsn4ml2ua]
null_resource.oci_metadata: Creating...
null_resource.oci_metadata: Provisioning with 'local-exec'...
**null_resource.oci_metadata (local-exec): Executing: ["/bin/sh" "-c" "echo 10.1.11.66 >> metadata.txt"]**
null_resource.oci_metadata: Creation complete after 0s [id=3798835019634380495]

**Error: Provider produced inconsistent final plan**

**When expanding the plan for oci_objectstorage_object.metadata to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/oci" produced an invalid new value for
.content: was cty.StringVal("25ab3be7aa1d92ae0a413bbefe467541"), but now
cty.StringVal("8e81b15ae62e61e934c6c28dec34bd0e").**

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This issue occurring only when object(file) being uploaded to object storage is dynamically updated by templates and then uploaded.

**Comment by srishtipmishra** [comment] 2020-11-12 17:06
@chandrashekhar-linux - Thanks for reporting this. I was able to reproduce the issue on my side. We're investigating further and will update the thread.

**Comment by srishtipmishra** [comment] 2020-11-14 03:11
@chandrashekhar-linux  - I wrote a config similar to yours to reproduce this error. During first apply all the resources including metadata text file get created successfully. However, there is a diff in plan just before apply as metadat.txt is empty and the plan when object is being created. This leads to an error in creating object. 

Currently, the workaround to this is quite simple - run terraform apply a second time and object gets provisioned successfully since metadat.txt now has content that doesnt change during apply. Let us know if this works for you. We're looking into a fix for this issue further.

**Comment by parrneet** [comment] 2020-11-20 16:52
@chandrashekhar-linux closing due to no action. Feel free to reopen if issue still exists.

**Closed by parrneet** 2020-11-20 16:52 UTC
Labels: bug
